### ISSUE TITLE
Locking a layer and using a keypress that includes a ctrl causes ctrl to be continuously pressed.

### ISSUE THREAD

**Issue by josh-hernandez-exe** [UltimateHackingKeyboard/agent#726] opened 2018-07-15 18:28 UTC
This is most evident while using an internet browser (I was using chrome `67.0.3396.99`), while using Windows 10.

Using:
- Agent version: `1.2.5`
- Firmware `8.2.5`

Steps:
1) Set [`ctrl`+`pgdn`] to `R` key on the mouse layer.
2) Lock into mouse layer.
3) Press the `R` key which send the keystrokes for [`ctrl`+`pgdn`].
4) Then press the `Y`/`H` keys to scroll up or down (based off the default mouse layer config). Instead of scroling on the page, I am zooming in and out (which is triggered with `ctrl`+`scrol up/down`). The behavior that I expected is that the page would scroll. Note that I was at no point was I pressing the modifier key while scrolling.

Further Testing:
1) This can happen with any modifer key (`shift`, `alt`, `super`).
	- For example, if I added a keystrokes [`alt`+`tab`] to the `V` key on the mouse layer and repeated the experiment but pressed `V` instead, `alt` will be held down.
	- There are some inconsistancies between the modifier keys:
		- `shift`, `super` was only pressed if that key was also on that layer.
			- Tested by adding [`ctrl`+`shift`+`tab`] and [`super`+`tab`] to the mouse layer then either leaving or removing `shift`/`super` from the layer.
		- `ctrl`, `alt` was held down regardless if they were in the layer or not.
			- Test by adding [`ctrl`+`pgdn`] and [`alt`+`tab`] then either removing the associated modifier from the layer.
2) Part of me doesn't actually know if the key is getting held down, or is pressed repeatedly.
	- This is becuase my tests with `ctrl` seem to do as I expect, but tests with `alt` don't seem to have the behavior I expect, but `http://keyboardchecker.com/` seems to tell me that `alt` is being pressed.
3) Unlocking the layer (reverting back to the base layer) seems to release the key.

**Comment by mondalaci** [comment] 2018-07-15 19:23
Thanks for reporting! Closing this because it's a duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/119

**Closed by mondalaci** 2018-07-15 19:23 UTC
