### ISSUE TITLE
Fn Volume Control has very coarse granularity

### ISSUE THREAD

**Issue by Ashod** [UltimateHackingKeyboard/agent#721] opened 2018-07-09 00:25 UTC
While the media controls work just fine, the volume control is quite hard to use as it is very coarse. For me the fastest I can manage makes it jump by ~30% or so in either direction. I couldn't find a way to control the granularity/sensitivity. As it is, I find it unusable (unless I need to maximize the volume, which I find it exceedingly unlikely, or to mute it--but there is a separate button for that).

Would be best to add configuration to add the speed of issuing repetition of volume control keys as I think different users will have different preference.

**Comment by mondalaci** [comment] 2018-07-09 00:32
Duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/72. We'll release a new firmware version soon that will contain the fix.

**Closed by mondalaci** 2018-07-09 00:32 UTC

**Comment by llinfeng** [comment] 2019-08-09 17:37
It never occurred to me that I should update the firmware on UHK :) Here goes a quick screenshot.

![image](https://user-images.githubusercontent.com/5890407/62797802-9778e500-baaa-11e9-9749-9112d822b23e.png)
