### ISSUE TITLE
More F-keys?

### ISSUE THREAD

**Issue by pukku** [UltimateHackingKeyboard/agent#224] opened 2016-12-16 02:35 UTC
Hi! My current keyboard has something like 19 F-keys. Could you add more scan codes for additional F-keys, even though there isn't space to have all of them active at once? This could be useful to tie in with things like Keyboard Maestro or BetterTouchTool...

**Comment by fjozsef** [comment] 2016-12-16 07:10
Hi! 
It has been added in 9807c5b7. Also duplicate of #218

**Closed by fjozsef** 2016-12-16 07:10 UTC
