### ISSUE TITLE
"Save configuration" required after updating to Agent 1.5.13 and firmware 8.10.9

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#1526] opened 2021-05-20 10:15 UTC
I updated to Agent 1.5.13 today (cannot remember from which Agent version, sorry), and flashed firmware 8.10.9 (updated from firmware 8.10.8). After that, my UHK v1 had the mouse layer switch mapped to the wrong key and was not working correctly.

I then chose my default keymap in Agent, changed one key without really changing anything (to get the "Save" button), and saved the (unchanged) configuration back to the keyboard. Now everything is working fine again.

I don't think the extra "save" should have been required after the upgrade.

**Comment by mhantsch** [comment] 2021-05-20 10:16
This may be the same root cause as #1493.

**Comment by mondalaci** [comment] 2021-05-23 20:21
This must be a duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/361

**Closed by mondalaci** 2021-05-23 20:21 UTC

**Comment by mhantsch** [comment] 2021-06-07 16:04
Just for reference, same issue happened again when updating from firmware 8.10.9 to 8.10.10 (without any change in Agent).
