### ISSUE TITLE
Weird behaviour - 1.4.5

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#1267] opened 2020-06-03 17:39 UTC
I've just ran into a bunch of weird problems today. Unfortunately, none seems reproducible, so feel free to close this once read.

I was basically just editing some macros. 
- I have noticed that spawning new windows is still an issue. Unfortunately, I achieved that accidentally and have no idea what shortcut I used (It was some modifier and some mouse button). I didn't pay attention to this.
- At some point, I have noticed that one of my macros (created by duplication and deletion of unwanted actions) contained actions which I believed to have deleted. In this, I may be mistaken.
- After that, I have deleted all actions in the macro and found out that I was no longer able to add a new action. 
- I changed view. At that point, content of the left pane dissapeared as if all macros and keymaps were deleted. 
- I tried to backup user config first and then save the config into UHK. At this point agent hanged on the saving procedure and I was forced to kill it (after giving it a few minutes).
- Also, I am sure I have deleted more stuff than added, yet the bar measuring config size claims 33kb.

![2020-06-03-192422_3840x2160_scrot](https://user-images.githubusercontent.com/3447497/83669156-633e5a00-a5d1-11ea-92e9-c7a140a7ed7f.png)

**Comment by mondalaci** [comment] 2020-06-03 20:29
Thanks for your detailed report! Unfortunately, I'm unable to reproduce these issues, so I'm closing this one. Please follow up if you manage to reproduce either of these issues.

**Closed by mondalaci** 2020-06-03 20:29 UTC
