### ISSUE TITLE
Add "Live View"

### ISSUE THREAD

**Issue by devployment** [UltimateHackingKeyboard/agent#1303] opened 2020-07-16 15:10 UTC
I think I'm what is called as a visual learner. As I'd like to learn a new layout, it would be helpful to me if the Agent could show a "Live View" of my current keyboard actions.

What does "Live View mean? Basically

* Be able to show the current keyboard interactions
* If enabled, show all key strokes in the agent coming in from the UHK
* if enabled, switch view to layer currently activated through the UHK

By this, i could have the agent running on a add. monitor and always see my current typing and the keys on the layer.

I'd like to contribute this feature on my own. Either just for me, or for everybody if it might be something useful for others :)

It would be helpful if somebody could give me a quick primer where to start. As Angular/Electron is not my strongest platform I might need some initial pointers, on how to start this at best.

**Comment by mondalaci** [comment] 2020-07-16 23:16
Thanks for your suggestion! I consider this issue essentially a duplicate of #1227, so I'm closing it in favor of it.

Also thanks for offering your help, but Angular/Electron and related APIs are quite vast, so realistically speaking, there's no quick primer for them. We'll make #1227 happen.

**Closed by mondalaci** 2020-07-16 23:16 UTC
