### ISSUE TITLE
Agent hangs on windows startup

### ISSUE THREAD

**Issue by sonictk** [UltimateHackingKeyboard/agent#529] opened 2017-12-25 00:21 UTC
Hi all:

I am part of the pilot run and got my UHK yesterday. I installed agent from the website: 1.0.1, and managed to successfully run it the first time and test out configuration of a custom keymap, which I then saved onto my UHK. However, upon subsequent launches of Agent, the app immediately hangs and cannot get past a white screen. Re-installing Agent (and clearing out the ``%localappdata%\Programs\uhk-agent\resources\packages``) did not help.

The only diagnostic output I could get when running the agent exe from a console window was: 

```
[16:12:52.909] [info] [Electron Main] Create new window.
[16:12:52.914] [info] [Electron Main] packagesDir: C:\Users\sonictk\AppData\Local\Programs\uhk-agent\resources
```

I am running W10 Pro with the Fall Creator's Update installed. Any information on how best this issue could be resolved would be appreciated (Especially since there's a lot more configuration I would like to be able to perform before I can consider using the keyboard in earnest!).

**Comment by mondalaci** [comment] 2017-12-25 00:43
Hi, and thank you for the report!

This seems a bit tricky given how short the log is. Can you do a screenshot of the Agent window?

Also, can you install Agent on another computer and try it with your keyboard? I'd like to now whether it works that way. If so, at least the EEPROM configuration of your UHK is not corrupted.

**Comment by sonictk** [comment] 2017-12-25 00:48
The screenshot isn't much; it basically just hangs after creating the window:

https://imgur.com/lB4le8Q

I will give it a go on my Linux machine later; unfortunately this is the only Windows machine I have access to over the break, however. I might try to do a bit of debugging on my own if I get the chance. Are there any other files or settings that Agent installs other than the location in ``%localappdata%``? I could try clearing those out as well.

**Comment by mondalaci** [comment] 2017-12-25 01:09
This seems very weird. By the looks of the log and the screenshot, electron hangs very early on before doing any actual work. Even though I'm not a Windows expert, I don't know of any settings or files other than `%localappdata%` that might affect this.

What's your take on this, @ert78gb?

Glad to reply early! I'm eager to get bugs fixed ASAP. Now it's quite easy with 50 UHKs out there, but we'd get totally flooded after sending out 2,000 UHKs.

Waiting on your findings about how it works on other computers.

**Comment by sonictk** [comment] 2017-12-25 01:30
I'm happy to report that Agent appears to work correctly on my Ubuntu 17.04 (GNOME) laptop (HP ZBook Studio 15 G4). I was able to continue configuration of my UHK from there and update my keymap; I will test on my Macbook Pro when I get a chance to see about OSX as well.

Is there a way to build a debug version of Agent with the debug version of the CRT DLLs etc, so that maybe I could try running the profiler again and perhaps seeing what actual calls might be causing the stall? Alternatively, if you guys could provide me with instructions how on how to debug this via node, I could try to give that a shot as well (though I'm not a node.js/electron dev, so you'd have to hold my hand a bit)

Thanks again for responding!

**Comment by ert78gb** [comment] 2017-12-25 10:36
I think it is not agent specific problem. https://github.com/electron/electron/issues/10863
Could you start the app with --disable-gpu option? Is it solve the problem until we solve the final solution?

**Comment by sonictk** [comment] 2017-12-26 04:15
@ert78gb I think I have repro steps now: 
- Fresh install of UHK Agent after reboot works.
- Do any configuration and _save the keymap to the keyboard_. 
- Now after clicking around a bit, Agent will hang. Subsequent attempts to launch Agent will also hang until after a reboot.

If I only launch Agent without saving the keymap, things seem fine when I attempt to launch Agent a second time.

**Comment by mondalaci** [comment] 2017-12-27 02:30
I've tried to reproduce this according to your instructions, but I couldn't.

I tried it on a stock Windows 10 Pro without installing the Fall Creator's Update. I'd rather not install the update because I assume that most users don't have it installed, so a stock Windows is more relevant for testing purposes as far as the majority is concerned.

Would you be able to try to reproduce this on multiple Windows 10 Pro machines, some having the Fall Creator's Update, and some doesn't? It'd expect that the Fall Creator's Update is responsible for this, or possibly some other installation-specific setting / DLL.

**Comment by mondalaci** [comment] 2018-01-05 17:01
@sonictk Were you able to reproduce this on another Windows installation, or possibly fix it on yours? I'm curious whether this problem is a one-off.

**Comment by sonictk** [comment] 2018-01-06 23:33
@mondalaci Unfortunately, I only have this W10 machine at home to test on; at work my machine is on W7 and the issue does not present itself there. I've noticed that a restart of the OS every time the issue happens does resolve it though!

**Comment by mondalaci** [comment] 2018-01-07 02:54
@sonictk So are you saying that if you restart your Windows 10 installation, Agent works, then after you close Agent, it doesn't work anymore until another restart? Please elaborate on this, I'd like to understand it.

**Comment by sonictk** [comment] 2018-01-07 08:40
@mondalaci So after a fresh restart of Win 10, the first time I launch Agent will be fine; so will subsequent times. However, if during any of those sessions of Agent where I'm able to launch it, I save a keymap, it triggers the issue where subsequent launches of Agent will present the hang on startup.

**Comment by mondalaci** [comment] 2018-01-08 04:09
Thanks for the further info! Do you use a USB hub to connect your UHK to your Windows 8 computer? If so, please try to connect your UHK directly without a hub. Please also give every USB port of your computer a try to see if you can always reproduce it. Waiting for your findings!

**Comment by sonictk** [comment] 2018-01-09 22:25
@mondalaci In this case, I tested while connecting through my KVM and connecting directly via the motherboard USB ports. Both presented the same issue (I don't have a Win8 machine BTW, only Windows 10). I'll try with some of the other ports like the front panel ones later tonight if I have the time.

**Comment by mondalaci** [comment] 2018-01-09 22:34
So are you running Windows 8 inside of a hypervisor? That can potentially make quite a difference. It'd be really nice to test this by running Windows 8 without a hypervisor. Can you do that?

**Comment by sonictk** [comment] 2018-01-17 17:58
@mondalaci No...sorry, I should specify I'm using a KVM *switch*, not a hypervisor. :P Sorry for the confusion.

I'm using my UHK at work for the time being though, I'll have to bring it back one of these weekends to record the issue.

**Comment by mondalaci** [comment] 2018-01-17 21:30
Oh, I see! Please definitely try your UHK without the KVM switch as it can be a major contributor to this issue.

I don't really need priority labels. I can manage these issues fairly well without them.

**Comment by mondalaci** [comment] 2018-02-12 16:18
This seems to be a one-off and specific to a single installation, so I'm closing it. Feel free to comment further.

**Closed by mondalaci** 2018-02-12 16:18 UTC
Labels: bug

**Comment by sonictk** [comment] 2018-04-14 21:53
@mondalaci BTW, sorry for the long delay, but I did manage to confirm that this occurs when connecting via KVM switch (Avocent). Strangely enough, it only seems to happen on this brand; when I connect via the KVM switch in the office (IOGear), it doesn't seem to have the same issue and Agent launches just fine.

**Comment by mondalaci** [comment] 2018-04-16 11:31
@sonictk Thanks for the feedback! It's good to know about this issue. It looks like some KVM switches and even some USB hubs screw up communication between Agent and the host. I think I'll create a FAQ about this eventually.
