### ISSUE TITLE
linux: agent stalled at start, no external usb hub

### ISSUE THREAD

**Issue by fortaa** [UltimateHackingKeyboard/agent#1178] opened 2020-02-27 13:41 UTC
1.4.2 does not work, hangs right after the AppImage window pops up
1.2.12 works in the same environment.

I connected directly to an embedded USB hub of my host, so I don't think it is a duplicate of #711 

```
$ lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/6p, 5000M
    |__ Port 1: Dev 34, If 0, Class=Hub, Driver=hub/4p, 5000M
        |__ Port 4: Dev 35, If 0, Class=Vendor Specific Class, Driver=r8152, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/12p, 480M
    |__ Port 1: Dev 108, If 0, Class=Hub, Driver=hub/4p, 480M
    |__ Port 2: Dev 109, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
    |__ Port 3: Dev 112, If 0, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 3: Dev 112, If 1, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 3: Dev 112, If 2, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 3: Dev 112, If 3, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 3: Dev 112, If 4, Class=Human Interface Device, Driver=usbhid, 12M
    |__ Port 6: Dev 3, If 0, Class=Video, Driver=uvcvideo, 480M
    |__ Port 6: Dev 3, If 1, Class=Video, Driver=uvcvideo, 480M
    |__ Port 8: Dev 4, If 1, Class=Wireless, Driver=btusb, 12M
    |__ Port 8: Dev 4, If 0, Class=Wireless, Driver=btusb, 12M

$ cat /etc/udev/rules.d/50-uh60.rules 
# Ultimate Hacking Keyboard rules
# tested with both rule sets
#SUBSYSTEM=="input", GROUP="input", MODE="0666"
#SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", MODE:="0666", GROUP="uucp"
#KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", MODE="0666", GROUP="uucp"

SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"
```

[agent_start.1.2.12.log.gz](https://github.com/UltimateHackingKeyboard/agent/files/4261860/agent_start.1.2.12.log.gz)
[agent_stalled_at_start.1.4.2.log.gz](https://github.com/UltimateHackingKeyboard/agent/files/4261861/agent_stalled_at_start.1.4.2.log.gz)

**Comment by mondalaci** [comment] 2020-02-28 16:47
1. Which is the latest Agent version that works for you?
2. Which distribution (name and version) are you using?

**Comment by fortaa** [comment] 2020-03-02 21:39
> 1. Which is the latest Agent version that works for you?

1.2.12 works. Narrowing the scope to the most recent ones I've tested 1.4.[12] only. Both failed. You might give me a hint which 1-2 releases I could give a try. I cannot perform agent QA thoroughly unfortunately. Alternatively name a Linux distro which you are certain the latest release of the agent works with flawlessly.

> 2. Which distribution (name and version) are you using?
>
Arch Linux (there is no version). Maybe the following might turn out to be useful:

```
$ ps -eo pid,cmd|grep '[U]HK'
 571824 /tmp/.mount_UHK.AgpNie2O/uhk-agent-ui --no-sandbox
 571828 ./UHK.Agent-1.4.2-linux-x86_64.AppImage
 571833 /tmp/.mount_UHK.AgpNie2O/uhk-agent-ui --type=zygote --no-sandbox
 571857 /tmp/.mount_UHK.AgpNie2O/uhk-agent-ui --type=gpu-process --field-trial-handle=10916229856192169310,10537177246140196320,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --no-sandbox --gpu-preferences=IAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --service-request-channel-token=42002444456658747
 571881 /tmp/.mount_UHK.AgpNie2O/uhk-agent-ui --type=renderer --no-sandbox --field-trial-handle=10916229856192169310,10537177246140196320,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --lang=en-US --app-path=/tmp/.mount_UHK.AgpNie2O/resources/app.asar --node-integration --no-sandbox --no-zygote --background-color=#fff --num-raster-threads=2 --enable-main-frame-before-activation --service-request-channel-token=15568259139940691173 --renderer-client-id=4 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100,v8_natives_data:101

$ for uhk_pid in $(ps -eo pid,cmd|grep '[U]HK'|awk '{print $1}'); do awk '{print $6}' /proc/$uhk_pid/maps|sort|uniq|grep -E 'UHK|.*\.so.*' > /tmp/mmaps.$uhk_pid.log; done
```

[mmaps.571828.log](https://github.com/UltimateHackingKeyboard/agent/files/4278029/mmaps.571828.log)
[mmaps.571881.log](https://github.com/UltimateHackingKeyboard/agent/files/4278030/mmaps.571881.log)
[mmaps.571857.log](https://github.com/UltimateHackingKeyboard/agent/files/4278031/mmaps.571857.log)
[mmaps.571833.log](https://github.com/UltimateHackingKeyboard/agent/files/4278032/mmaps.571833.log)
[mmaps.571824.log](https://github.com/UltimateHackingKeyboard/agent/files/4278033/mmaps.571824.log)

**Comment by mondalaci** [comment] 2020-03-03 09:10
The latest Agent version works on Linux Mint 19.3.

I'm sorry, but the logs you attached don't help, and I can't figure out the root cause if you can't tell the most recent Agent version that stopped working, so I'm closing the issue.

Feel free to follow up, and I will reopen the issue if I get more useful information.

**Closed by mondalaci** 2020-03-03 09:10 UTC
