### ISSUE TITLE
'Type text' box in macro editor doesn't accept clipboard data on Mac

### ISSUE THREAD

**Issue by p4elkin** [UltimateHackingKeyboard/agent#808] opened 2018-10-04 14:26 UTC
I have been trying to implement a macro that types shruggie emoji ( ¯\ _(ツ)_/¯ ) by copying it to the box mentioned in the issue title. However, I realised that it wouldn't let me paste the text in (and I am too lazy to figure out how to _actually_ type that emoji ¯\ _(ツ)_/¯).

**Comment by mondalaci** [comment] 2018-10-04 15:54
This will never work this way. The reason is that USB keyboards don't output characters, but scancodes. You have to understand on the high level how USB keyboards work. See https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk

**Comment by p4elkin** [comment] 2018-10-04 16:49
Hm, yeah, albeit being a good use case [imo], shruggie might be a confusing example. But the point of the ticket is that I cannot paste _any_ text into the textbox while crafting my macro. Potential useful case would be e.g. some bulky file header that one would like to easily insert to the source file or smth.

To emphasize - I was not talking of assigning a Unicode char to a key, rather about this:
<img width="700" alt="default" src="https://user-images.githubusercontent.com/1240136/46489502-350de300-c80e-11e8-8287-017ffbbded58.png">

**Comment by mondalaci** [comment] 2018-10-04 17:05
Just tried it, and I could paste "foobar" into the textbox. Which OS are you using?

**Comment by p4elkin** [comment] 2018-10-04 18:53
I'm on Macos 10.12.6 (Sierra). Btw, I just tried on my Ubuntu VM and there I am able to paste the text just fine.

**Comment by mondalaci** [comment] 2018-10-04 19:09
I can confirm it works fine on Linux and Windows and doesn't work on Mac.

**Comment by ert78gb** [comment] 2018-10-07 16:14
I use Mac Mojave and I could paste any ASCII text into the textarea.
The [line](https://github.com/UltimateHackingKeyboard/agent/blob/425147745184b39f660d5e0b2c55d7cd51ee89d2/packages/uhk-web/src/app/components/macro/action-editor/tab/text/macro-text.component.ts#L61) filter the non-ASCII characters.

@mondalaci could u test it in Mac Mojave and if it works for you also what is the future of this issue?

**Comment by mondalaci** [comment] 2018-10-07 16:19
I can only test and reproduce this on OSX 10.9.5.

Do you have any idea how to fix this?

**Comment by mondalaci** [comment] 2018-10-07 16:30
In the meantime, I chat with @ert78gb and he told me that he can't reproduce this issue and doesn't know what the root cause might be. I'm closing this because eventually everybody will update to a newer OSX version at which point this issue will become irrelevant.

**Comment by eltang** [comment] 2018-10-07 16:48
I am experiencing this issue with macOS Mojave. In my case, all of Agent's text boxes are affected, and the copy, paste, cut, and select all operations all don't work.

**Comment by ert78gb** [comment] 2018-10-07 16:52
@eltang u r right. The shortcuts are not working in the built version. I tested earlier in the developer version `npm run electron` the main difference between the 2 version are the menu. I am talking with @mondalaci about the possibilities

**Closed** 2018-10-07 19:02 UTC
Labels: bug

**Comment by eltang** [comment] 2018-10-07 20:16
I can verify that I can perform the aforementioned operations by using keyboard shortcuts, but I would like to also be able to right-click on the text box and select them from a context menu.
