### ISSUE TITLE
Left half keyboard can not connect - no LEDS or keystrokes

### ISSUE THREAD

**Issue by jokem59** [UltimateHackingKeyboard/agent#1803] opened 2022-06-21 18:46 UTC
I've just received my UHK v2 in the mail today and upon plugging the merged keyboard (also unmerged with provided connecting cable), the keyboard worked as intended.  As I worked through the keyboard introduction via the online manual, the left half of the keyboard LEDs stopped working and no key presses were being detected.  Oddly, when plugging in the left key cluster, the key cluster lights up and Agent also detects it.

Per the closed issues on github, I've attempted updating the firmware by starting with JUST the right half plugged in, then plugging in the left half (also tried via Merging the keyboards together).  Each attempt fails to connect to the Left Keyboard Half with the attached error.  Agent is running on Ubuntu.

Other debugging methods attempted:
  - Try different USB ports (A and C)
  - Use the UHK provided USB cable and some of my own
  - Try USB hub
  - Try while laptop is on/off power supply
  - Try other machines running Ubuntu
  - Try on Windows machine

Also, when plugging in the connected UHK with the key cluster module, Agent detects the right half AND the key cluster module.  It does NOT detect the left half keyboard.

Is there something else I can attempt to debug this?
[uhk_error.txt](https://github.com/UltimateHackingKeyboard/agent/files/8951983/uhk_error.txt)

EDIT: I also sent an email to support@ultimatehackingkeyboard.com, but wanted to share here so others can benefit from anything that might help restore the left half keyboard.

**Comment by lo48576** [comment] 2022-06-24 19:38
Maybe this wouldn't help, but I share this FYI...

I've experienced left-half bricking of my UHK **v1**, without modules, at 2020-11-01. At that time, firmware version is 8.10.0 or something like that.

At that time, I suffered from USB bug related to Ryzen CPU. Due to that bug, USB connection to the keyboard intermittently disconnected. I tried to upgrade the firmware to mitigate the problem... and USB disconnected during the firmware write!
The left half seemed to brick... device became undetectable, and LED didn't work. I've sent an e-mail to support, but no I received no response (or possibly my mail server rejects it unexpectedly...).

After an year (2022-11-03), I tried to update agent and firmware (8.10.12), and then left half started to work again! I don't have any idea why the left half revived (hardware reason, or firmware and agent update?), but anyway my UHK revived.

So what I can say is: Don't lose hope. Even your device seems to be bricked and you cannot get any useful workaround right now, it might be (theoretically) possible to repair with newer UHK agent and firmware in future.

Reference (Japanese SNS posts):
* https://mastodon.cardina1.red/@lo48576/105134647075472648
    + Me saying "oh no" (with screen capture of UHK agent failing to write firmware)
* https://mastodon.cardina1.red/@lo48576/107209826493605622
    + Me saying "Left half of UHK 60 v1 bricked just one year ago, but today I suddenly updated UHK Agent and also updated the firmware of right half to 8.10.2 (current latest), then left half revived! :tada:"

**Comment by jokem59** [comment] 2022-06-24 19:41
I appreciate the encouragement =)  I'm currently running Agent 1.5.17 and trying to update with firmware 8.10.12 with no luck at the moment.

**Comment by lo48576** [comment] 2022-06-24 19:44
One more thing: If you have any idea why (or by what operation/event) it stopped working, https://github.com/UltimateHackingKeyboard/firmware would be the better place to report.

**Comment by jokem59** [comment] 2022-06-24 21:11
Thanks @lo48576, the left half keyboard stopped working shortly after I first plugged it in.  I got through the UHK online tutorial/manual (just past the mouse layer section I believe) and the left half went dead.  At that point, I had not played with Agent or the firmware.

**Comment by kareltucek** [comment] 2022-06-24 22:02
@jokem59 while waiting for Laszlo's help, feel free to give a try to the instructions in https://ultimatehackingkeyboard.com/knowledgebase with "bricked" as a search term. Definitely do ***not*** wait a whole year before bumping the mail/ticket if there is no reply :).

(The reconnecting procedure can take a many of attempts - even numbers like 50. I am not sure about the "right-click" reliability, but I guess it should be much more reliable, given that the consequent flashing succeeds.)

As to the repos, both repos are just fine - chances are that this is device/installation specific issue, so does not really relate to development in either of the repositories. (General discussion usually goes on here.)

> Oddly, when plugging in the left key cluster, the key cluster lights up and Agent also detects it.

Might be relevant to debug the issue, but it is not surprising. It stands to reason that the I2C bus as well as power goes straight through the left half, without its MCU having to copy the messages onto a separate hardware bus...

**Comment by jokem59** [comment] 2022-06-24 22:46
@kareltucek - thanks for the pointer.  I've worked my way up to 50 reconnects.  To make sure I'm doing the right thing, here's my workflow:

1. Start with just the right half plugged in
2. Run firmware update from agent
3. When prompted to connect the left half, I physically merge the two halves together
4. Agent begins trying to connect to left half
5. Agent times out

The other method of "right- clicking" in agent to try and update firmware on just one half doesn't seem to be supported in the latest version of agent (v 1.5.17).

**Comment by mondalaci** [comment] 2022-06-25 12:12
@lo48576 We usually reply in a work day, so your email probably got lost. In such a rare case, feel free to message us on Twitter. As @kareltucek correctly mentioned, bricked UHKs can usually be restored based on the instructions of https://ultimatehackingkeyboard.com/knowledgebase?q=bricked

@jokem59 The root cause of such issues is usually power-related, and it's worth narrowing down the cause based on points 1 to 10 of [this guide](https://ultimatehackingkeyboard.com/repair/fixing-misbehaving-keys). I can see that my colleague also provided this instruction to you in email, but she didn't include point 10, which may solve such issues. But in your case, the issue is probably hardware-related, so worst-case scenario, we'll recall your UHK. Feel free to follow up in email regarding the recall. In the meantime, let's continue this discussion here instead of email, as using two communication channels is rather counter-productive.

**Comment by jokem59** [comment] 2022-06-25 17:18
Thanks @mondalaci - I've attempted step 10 per the guide (turned off all LEDs) in the following manner.  All attempts are done with both halves merged without the connecting cable as well as starting with just the right half, and then physically merging the keyboards per the Agent prompt.

- UHK plugged directly into Ubuntu Laptop on main power via USB A adapter
- UHK plugged directly into Ubuntu Laptop on main power via USB C adapter
- UHK plugged directly into Ubuntu Laptop on battery power via USB A adapter
- UHK plugged directly into Ubuntu Laptop on battery power via USB C adapter
- UHK plugged directly into Windows Desktop via USB A adapter

I've also played with various combinations of Agent and Firmware versions with no luck as well.

**Comment by mondalaci** [comment] 2022-06-25 17:43
@jokem59 Unfortunately, I'm out of ideas. My colleague will follow up in an email about the recall. I'm closing this issue because this looks like a hardware-related one, but you're welcome to follow up here and share your findings regardless.

**Closed by mondalaci** 2022-06-25 17:43 UTC
