### ISSUE TITLE
multimedia key next and previous do not seem to work on macos high siera 

### ISSUE THREAD

**Issue by RMHogervorst** [UltimateHackingKeyboard/agent#775] opened 2018-09-12 08:06 UTC
First of all, the keyboard is amazing and I love it!
but I can't get the music player to go to next track with Fn + Rarrow (L on my keyboard 2 from the button with mark on it)

I'm using the UHK with windows keycaps and set the mode to QWM. 
On a macbook pro 2015 macOS high Sierra 

What does work: everything else: volume up, volume, play/pause, mute. The next and previous do work on the mac function keys on the build in keys. (in QWR the function I have the same issues, all work except next previous).

I  figure the keyboard message isn't interpreted correctly. 
When I try to assign something to the keypress (fn right arrow) the applications don't seem to pick something up. 
Could there be a keypress for forwards and backwards? (it is not in the option to assign to a key)
Could I debug it myself? 

Thanks!

**Comment by RMHogervorst** [comment] 2018-09-12 08:06
I have not checked in on other devices, because I have only access to a mac at the moment

**Comment by RMHogervorst** [comment] 2018-09-12 08:15
shit, should this be in another repo?

**Comment by mondalaci** [comment] 2018-09-16 22:31
The previous track and next track scancodes work perfectly on my 2012 Macbook Pro. Any chance you misconfigured something? Please export your configuration in Agent and attach it.

**Comment by RMHogervorst** [comment] 2018-09-17 14:48
Is there a way for me to check what codes are emited? 
Attached is the config, which is standard I think

(I've renamed the file to .txt but it is the .json)
[UserConfiguration.txt](https://github.com/UltimateHackingKeyboard/agent/files/2389006/UserConfiguration.txt)

**Comment by RMHogervorst** [comment] 2018-09-17 15:01
I have  macbook pro retina early 2015. using high sierra 10.13.6

**Comment by mondalaci** [comment] 2018-09-17 15:41
I still can't reproduce, neither with the QWM, nor with the QWR keymap. Are you using iTunes? If not, please give it a try.

**Comment by RMHogervorst** [comment] 2018-09-18 08:51
Weird! the next and previous buttons do work in itunes but not in another player (clementine). While the buttons on the macbook itself work in both. (So I guess it's a player specific problem)

**Comment by mondalaci** [comment] 2018-09-18 11:49
This is weird, indeed. Maybe Clementine hotkeys can be configured. In any case, this doesn't seem like a UHK issue, so I'm closing this.

**Closed by mondalaci** 2018-09-18 11:49 UTC

**Comment by kareltucek** [comment] 2019-04-16 09:56
I've just noticed that there are scancode definitions for volume up/down in both standard report and in media report sets and it reminded me of this issue. I guess this is the reason for the strange anomaly...

**Comment by mondalaci** [comment] 2019-04-16 10:11
System and media scancodes often have basic scancode alternatives, but the latter only works on Linux, so the former should be used for cross-platform compatibility.
