### ISSUE TITLE
Make it possible to double tap shift to activate caps lock

### ISSUE THREAD

**Issue by gitgnmn** [UltimateHackingKeyboard/agent#856] opened 2018-11-13 09:44 UTC
I'd want to be able to double tap Shift to use Caps Lock. In the same way I lock the Mod, Fn and Mouse layers by double tapping respectable key.

It's long from a deal breaker (I love my UHK so far) but the other toggles feels more intuitive to me than having to use Mod+A to make my Shift-function "stick". This could possibly also be done by implementing #720(?).

**Comment by mondalaci** [comment] 2018-11-13 12:47
I think this feature has more cons than pros. You'd like to trigger Caps Lock in a more intuitive and easier manner, but this would inevitably lead to the unintended activation of Caps Lock every now and then.

I'm closing this because it's largely a duplicate of #720.

**Closed by mondalaci** 2018-11-13 12:47 UTC
