### ISSUE TITLE
Cannot flash custom firmware file

### ISSUE THREAD

**Issue by eltang** [UltimateHackingKeyboard/agent#606] opened 2018-04-11 09:13 UTC
I'm not sure if I'm doing something wrong, but I was unable to flash a custom firmware file using Agent 1.1.5.

After I clicked the button, I was able to browse for a firmware file. There were seemingly no restrictions on the types of file I could choose; I mistakenly chose a .elf file the first time, and it was silently accepted. In addition, I was not given any opportunity to indicate which half I wanted to flash.

**Comment by mondalaci** [comment] 2018-04-11 09:34
Agent only consumes a tarball of a special file hierarchy that contains the firmware of the right half, left half, add-ons, and the user configuration. See the released firmwares and the scripts/make-release.js script of the firmware repo.

We can't filter a specific file extension in the file open dialog because it's not possible in a cross-platform manner using web technologies.

When an invalid firmware file is supplied, Agent displays the "Invald configuration specified" error message in the top right corner. This works correctly for me. Isn't it displayed for you? If not, what can you see in the terminal / console upon supplying an invalid firmware file?

**Comment by eltang** [comment] 2018-04-11 09:38
I don't see any such message. For me the flashing process simply starts as if nothing was wrong.

**Comment by mondalaci** [comment] 2018-04-11 09:40
This is very weird. Can you attach a file to reproduce this? Still using Fedora?

**Comment by eltang** [comment] 2018-04-11 09:42
I simply compiled the latest firmware using KDS and selected the resulting .hex and .elf files.

**Comment by mondalaci** [comment] 2018-04-11 09:44
What can you see in the firmware update console when supplying an elf or hex?

**Comment by eltang** [comment] 2018-04-11 10:01
First I get this.
```
[02:36:43.646] [debug] [UhkOperations] Start flashing right firmware
[02:36:43.646] [debug] [UhkHidDevice] Start reenumeration, mode: Bootloader
[02:36:43.756] [debug] [UhkHidDevice] Available devices: [ { vendorId: 1118,
    productId: 64,
    path: '0003:0004:00',
    release: 289,
    interface: 0 },
  { vendorId: 7504,
    productId: 24866,
    path: '0003:001a:00',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'Ultimate Hacking Keyboard',
    release: 257,
    interface: 0 },
  { vendorId: 7504,
    productId: 24866,
    path: '0003:001a:01',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'Ultimate Hacking Keyboard',
    release: 257,
    interface: 1 },
  { vendorId: 7504,
    productId: 24866,
    path: '0003:001a:02',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'Ultimate Hacking Keyboard',
    release: 257,
    interface: 2 },
  { vendorId: 7504,
    productId: 24866,
    path: '0003:001a:03',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'Ultimate Hacking Keyboard',
    release: 257,
    interface: 3 },
  { vendorId: 7504,
    productId: 24866,
    path: '0003:001a:04',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'Ultimate Hacking Keyboard',
    release: 257,
    interface: 4 } ]
[02:36:43.758] [debug] [UhkHidDevice] Used device: { vendorId: 7504,
  productId: 24866,
  path: '0003:001a:00',
  manufacturer: 'Ultimate Gadget Laboratories',
  product: 'Ultimate Hacking Keyboard',
  release: 257,
  interface: 0 }
[02:36:43.759] [debug] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[02:36:43.759] [debug] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[02:36:44.335] [debug] [UhkHidDevice] reenumeration devices up
[02:36:44.336] [debug] [UhkHidDevice] Device communication closing.
[02:36:44.336] [debug] [UhkHidDevice] Device communication closed.
[02:36:44.338] [debug] [blhost] RUN: /tmp/.mount_UHK.AguaEnu2/app/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[02:36:44.418] [debug] [blhost] STDOUT: Inject command 'flash-security-disable'
Successful generic response to command 'flash-security-disable'
Response status = 0 (0x0) Success.

[02:36:44.421] [debug] [blhost] EXIT_CODE: 0
[02:36:44.422] [debug] [blhost] FINISHED: 0
[02:36:44.422] [debug] [blhost] RUN: /tmp/.mount_UHK.AguaEnu2/app/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-erase-region 0xc000 475136
[02:36:44.430] [debug] [blhost] CLOSE_CODE: 0
[02:36:45.716] [debug] [blhost] STDOUT: Inject command 'flash-erase-region'
Successful generic response to command 'flash-erase-region'
Response status = 0 (0x0) Success.

[02:36:45.718] [debug] [blhost] EXIT_CODE: 0
[02:36:45.719] [debug] [blhost] FINISHED: 0
[02:36:45.719] [debug] [blhost] CLOSE_CODE: 0
[02:36:45.719] [debug] [blhost] RUN: /tmp/.mount_UHK.AguaEnu2/app/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 flash-image "/tmp/tmp-23763RqsjVPUVIoxS/devices/uhk60-right/firmware.hex"
[02:36:45.786] [debug] [blhost] STDOUT: Inject command 'flash-image'
Error: unable to find file /tmp/tmp-23763RqsjVPUVIoxS/devices/uhk60-right/firmware.hex

[02:36:45.788] [debug] [blhost] EXIT_CODE: 0
[02:36:45.788] [debug] [blhost] FINISHED: 0
[02:36:45.788] [debug] [blhost] RUN: /tmp/.mount_UHK.AguaEnu2/app/resources/packages/blhost/linux/x86_64/blhost --usb 0x1d50,0x6120 reset
[02:36:45.797] [debug] [blhost] CLOSE_CODE: 0
[02:36:45.858] [debug] [blhost] STDOUT: Inject command 'reset'
Successful generic response to command 'reset'
Response status = 0 (0x0) Success.

[02:36:45.859] [debug] [blhost] EXIT_CODE: 0
[02:36:45.860] [debug] [blhost] FINISHED: 0
[02:36:45.860] [debug] [UhkOperations] Right firmware successfully flashed
[02:36:45.861] [debug] [UhkOperations] Start flashing left module firmware
[02:36:45.861] [debug] [UhkHidDevice] Start reenumeration, mode: NormalKeyboard
[02:36:46.238] [debug] [blhost] CLOSE_CODE: 0
```
Then I get a million of these.
```
[02:37:05.879] [debug] [UhkHidDevice] Available devices: [ { vendorId: 7504,
    productId: 24864,
    path: '0003:001c:00',
    manufacturer: 'Ultimate Gadget Laboratories',
    product: 'UHK Bootloader',
    release: 2,
    interface: 0 },
  { vendorId: 1118,
    productId: 64,
    path: '0003:0004:00',
    release: 289,
    interface: 0 } ]
[02:37:05.880] [debug] [UhkHidDevice] UHK Device not found:
```
Finally I get an error message.
```
[02:37:05.880] [debug] [UhkHidDevice] UHK Device not found:
[02:37:05.880] [error] [UhkHidDevice] Could not find reenumerated device: NormalKeyboard. Timeout
[02:37:05.882] [error] [DeviceService] updateFirmware error { message: 'Could not reenumerate as NormalKeyboard',
  stack: 'Error: Could not reenumerate as NormalKeyboard\n    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AguaEnu2/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:166:1)\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/.mount_UHK.AguaEnu2/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:4:42)\n    at <anonymous>' }
[02:37:06.388] [info] [ '[DeviceRendererService] dispatch action',
  '{"payload":{"error":{"message":"Could not reenumerate as NormalKeyboard","stack":"Error: Could not reenumerate as NormalKeyboard\\n    at UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AguaEnu2/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:166:1)\\n    at Generator.next (<anonymous>)\\n    at fulfilled (/tmp/.mount_UHK.AguaEnu2/app/resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:4:42)\\n    at <anonymous>"}},"type":"[device] update firmware reply"}' ]
```

**Comment by mondalaci** [comment] 2018-04-11 10:08
Thanks Eric. Does the firmware update process launch directly after you pressed the "Choose firmware file and flash it" button and selected the hex or elf file?

I don't get how this is possible because the firmware update process references files within the bundle, and in your case the "bundle" (elf or hex file) is invalid. It's as if you pressed the "Flash firmware x.y.z (bundled with Agent)" button.

**Comment by eltang** [comment] 2018-04-11 10:11
Yes, all this happens right after I click OK in the dialog window.

**Comment by eltang** [comment] 2018-04-11 10:27
Here they are.
[uhk-right.zip](https://github.com/UltimateHackingKeyboard/agent/files/1898407/uhk-right.zip)

**Comment by mondalaci** [comment] 2018-04-11 13:10
As it turns out, I was being fully retarded. I used the import configuration feature instead of the firmware update feature. Since then, I've got some sleep and my IQ is back from 0 to 50.

Just opened #608 which should take care of this in the future.

Sorry about this, and thanks a lot for your report! Closing this issue, but feel free to comment.

**Closed by mondalaci** 2018-04-11 13:10 UTC
