### ISSUE TITLE
1.2.12 udev hiccups

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/agent#867] opened 2018-11-20 15:23 UTC
Hi, I would like to report behaviour of my UHK after downloading 1.2.12 (on Arch linux). 

- I've never had problem with reaching UHK throught my hub before (as far as I remember).
- 1.2.12 required setting up udev rules even though UHK used to work fine before (note that this was with plugged hub). I've done that - I am not sure if something in the rules has changed. Even after that and a restart, agent wouldn't work, claiming that it cannot find UHK.
- After connecting UHK directly to the computer, agent started working....
- But the hub stopped working after I plugged the UHK back into it. No device connected to the hub did work. This state has survived even OS restart
- After disconnecting and reconnecting everything into different ports, all things started working magically again.

I don't know what happened and why, but I though you might like to know... 

Anyway, this is just for your information - please close the ticket once you read it and consider it solved (as far as I am concerned). Of course, I am available if you have any questions...

**Comment by mondalaci** [comment] 2018-11-20 16:07
The "Upgrade to node-hid 0.7.3 which utilizes the hidraw USB driver on Linux instead of libusb."  changelog entry of Agent 1.2.12 is the reason why we had to mess with the udev rules. The new rule file contains hidraw related rules, too.

We've put a great deal of effort into making the transition as smooth as possible, but given that the older libusb driver claims the UHK generic HID USB interface, hidraw can't access it right away, so reconnecting the UHK is required when switching to the new Agent.

USB hubs can produce [very unusual issues](https://github.com/UltimateHackingKeyboard/firmware/issues/68#issuecomment-353651482). I'm not surprised that yours does too, but I'm surprised that you can only experience it with hidraw, and not with libusb. Are you sure you can't reproduce this with libusb? Also, can you narrow down the hub issue?

**Comment by kareltucek** [comment] 2018-11-20 22:02
I am not sure how to reproduce it with either of them. I don't remember ever having problems with libusb-based agents (apart from crashing blhost), which doesn't necessarily mean that libusb works flawlessly. Now everything seems to work fine even with the hub and hidraw. 

(I still suggest simply closing this issue and ignoring it unless/until there is more reports of this kind.)

**Comment by mondalaci** [comment] 2018-11-20 22:03
Thanks for your further feedback! Closing this as suggested. Any issues, feel free to follow up.

**Closed by mondalaci** 2018-11-20 22:03 UTC

**Comment by kareltucek** [comment] 2018-11-20 22:05
Sure ;-)
