### ISSUE TITLE
Device connection state query error Error

### ISSUE THREAD

**Issue by diegoddox** [UltimateHackingKeyboard/agent#1876] opened 2022-10-25 14:13 UTC
An infinite loop of errors on the console

Agent version: 2.0.0
macOS Monterey, chip Apple M1.

![Screenshot 2022-10-25 at 15 55 14](https://user-images.githubusercontent.com/2768497/197796486-597e9aa6-cdb7-4683-ba5b-a2b58d8aef1c.png)

Error
`polyfills.3b4de067b1bda1ef.js:1 16:10:07.192 › [DeviceService] Device connection state query error Error: dlopen(/var/folders/5n/5ryv8nms5jjb8wvhgpwqrcmc0000gp/T/.com.ultimategadgetlabs.agent.SMiZfi, 0x0001): tried: '/var/folders/5n/5ryv8nms5jjb8wvhgpwqrcmc0000gp/T/.com.ultimategadgetlabs.agent.SMiZfi' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '/private/var/folders/5n/5ryv8nms5jjb8wvhgpwqrcmc0000gp/T/.com.ultimategadgetlabs.agent.SMiZfi' (mach-o file, but is an incompatible architecture`

**Comment by mondalaci** [comment] 2022-10-25 14:16
Duplicate of #1873.

**Closed by mondalaci** 2022-10-25 14:16 UTC
