### ISSUE TITLE
mouse speed assocated with keymaps

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [UltimateHackingKeyboard/agent#1416] opened 2021-01-26 16:35 UTC
#458 added customizable mouse speeds but it would be nice to be able set for each configuration since I switch between openbsd, mac, and windows often but each system has different mouse properties.

**Comment by mondalaci** [comment] 2021-01-26 18:06
Duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/300

**Closed by mondalaci** 2021-01-26 18:06 UTC
