### ISSUE TITLE
Linux [DeviceOperation] ValidatedUserConfig from eeprom error

### ISSUE THREAD

**Issue by enewbury** [UltimateHackingKeyboard/agent#1818] opened 2022-08-07 21:11 UTC
Agent version 1.5.17 Linux AppImage running on fedora 36

![image](https://user-images.githubusercontent.com/4422419/183311053-3c6de970-5c19-49fd-bb52-943722685b5d.png)

Logs
```
17:00:35.792 › [Electron Main] init services.
17:00:35.795 › [Electron Main] packagesDir: /tmp/.mount_UHK.AgzSPB1L/resources
17:00:35.975 › [Electron Main] Create new window.
17:00:35.975 › [WindowState] load settings
17:00:35.976 › [WindowState] loaded settings {
  x: 236,
  y: 629,
  width: 1024,
  height: 768,
  isMaximized: true,
  isFullScreen: false
}
17:00:35.977 › [WindowState] loaded settings is visible true
17:00:35.978 › [WindowState] return with loaded settings
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[98419:0807/170036.093528:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
17:00:36.152 › [DeviceService] init success
17:00:36.154 › [AppUpdateService] init success
17:00:36.155 › [AppService] init success
17:00:36.155 › [SudoService] App root dir:  /tmp/.mount_UHK.AgzSPB1L/resources
17:00:36.177 › [WindowState] save settings: {
  x: 0,
  y: 507,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
17:00:36.180 › [WindowState] save settings success
17:00:36.195 › [WindowState] save settings: {
  x: 236,
  y: 666,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
17:00:36.197 › [WindowState] save settings success
17:00:36.199 › [WindowState] load settings
17:00:36.199 › [WindowState] loaded settings {
  x: 236,
  y: 666,
  width: 1024,
  height: 768,
  isMaximized: false,
  isFullScreen: false
}
17:00:36.199 › [WindowState] loaded settings is visible true
17:00:36.199 › [WindowState] return with loaded settings
17:00:36.200 › [WindowState] save settings: {
  x: 236,
  y: 666,
  width: 1024,
  height: 768,
  isMaximized: true,
  isFullScreen: false
}
17:00:36.201 › [WindowState] save settings success
17:00:36.201 › [WindowState] load settings
17:00:36.214 › [WindowState] loaded settings {
  x: 236,
  y: 666,
  width: 1024,
  height: 768,
  isMaximized: true,
  isFullScreen: false
}
17:00:36.214 › [WindowState] loaded settings is visible true
17:00:36.215 › [WindowState] return with loaded settings
17:00:36.215 › [WindowState] save settings: {
  x: 236,
  y: 666,
  width: 1024,
  height: 768,
  isMaximized: true,
  isFullScreen: false
}
17:00:36.219 › [WindowState] save settings success
17:00:36.233 › [DeviceService] Udev info: Ok
17:00:36.510 › [AppService] get-config: application-settings
17:00:36.510 › [AppService] get-config of "application-settings": undefined
17:00:36.686 › [AppRendererService] init success 
17:00:36.694 › [DeviceRendererService] init success 
17:00:36.696 › Renderer appStart effect start
17:00:36.696 › [AppRendererService] getAppStartInfo
17:00:36.696 › [AppService] getAppStartInfo
17:00:36.696 › Renderer appStart effect end
17:00:36.697 › [AppService] get-config: application-settings
17:00:36.697 › [AppUpdateService] check for update at startup: { checkForUpdateOnStartUp: true }
17:00:36.698 › [AppUpdateService] app started. Automatically check for update.
17:00:36.698 › Checking for update
17:00:36.698 › [AppUpdateService] checking for update
17:00:36.698 › sendIpcToWindow: checking-for-update null
17:00:36.703 › [AppService] getAppStartInfo response: {
  commandLineArgs: { modules: false },
  platform: 'linux',
  osVersion: '5.18.15-200.fc36.x86_64',
  udevFileContent: '# Ultimate Hacking Keyboard rules\n' +
    '# These are the udev rules for accessing the USB interfaces of the UHK as non-root users.\n' +
    '# Copy this file to /etc/udev/rules.d and physically reconnect the UHK afterwards.\n' +
    'SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"\n' +
    'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n' +
    'KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n'
}
17:00:36.703 › [AppService] get-config of "application-settings": undefined
17:00:36.849 › [AppRendererService] dispatch action: [app] process start info
17:00:36.850 › [AppEffect][processStartInfo] payload: {
  commandLineArgs: { modules: false },
  platform: 'linux',
  osVersion: '5.18.15-200.fc36.x86_64',
  udevFileContent: '# Ultimate Hacking Keyboard rules\n' +
    '# These are the udev rules for accessing the USB interfaces of the UHK as non-root users.\n' +
    '# Copy this file to /etc/udev/rules.d and physically reconnect the UHK afterwards.\n' +
    'SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"\n' +
    'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n' +
    'KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n'
}
17:00:36.852 › [DeviceService] start poll UHK Device
17:00:36.928 › [UhkHidDevice] Devices before checking permission:
17:00:36.933 › [UhkHidDevice] Available devices changed.
17:00:36.933 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
17:00:36.933 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw2","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":1,"usagePage":1,"usage":6}
17:00:36.934 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw5","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":2,"usagePage":12,"usage":1}
17:00:36.934 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":3,"usagePage":1,"usage":128}
17:00:37.002 › [UhkHidDevice] Available devices unchanged
17:00:37.054 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
17:00:37.074 › [DeviceOperation] Read "leftHalf" version information
17:00:37.085 › [DeviceService] Device connection state changed to: {
  bootloaderActive: false,
  zeroInterfaceAvailable: true,
  hasPermission: true,
  halvesInfo: {
    areHalvesMerged: false,
    isLeftHalfConnected: true,
    leftModuleSlot: 0,
    rightModuleSlot: 0
  },
  hardwareModules: {
    moduleInfos: [ '[object]' ],
    rightModuleInfo: {
      firmwareVersion: '8.10.12',
      deviceProtocolVersion: '4.7.1',
      moduleProtocolVersion: '4.1.0',
      userConfigVersion: '4.2.0',
      hardwareConfigVersion: '1.0.0'
    }
  },
  multiDevice: false,
  connectedDevice: {
    id: 2,
    name: 'UHK 60 v2',
    vendorId: 7504,
    keyboardPid: 24868,
    bootloaderPid: 24867,
    buspalPid: 24865
  }
}
17:00:37.085 › [DeviceRendererService] dispatch action [device] connection state changed
17:00:37.089 › [DeviceService] stop poll UHK Device
17:00:37.090 › [DeviceService] stopped poll UHK Device
17:00:37.092 › [UhkHidDevice] Device communication closing.
17:00:37.093 › [UhkHidDevice] Device communication closed.
17:00:37.093 › [DeviceService] start poll UHK Device
17:00:37.093 › [DeviceService] stop poll UHK Device
17:00:37.093 › [DeviceService] stopped poll UHK Device
17:00:37.096 › [UhkHidDevice] Available devices unchanged
17:00:37.149 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
17:00:37.103 › [DeviceRendererService] dispatch action [device] Read config sizes reply
17:00:37.155 › [UhkHidDevice] Device communication closing.
17:00:37.156 › [UhkHidDevice] Device communication closed.
17:00:37.156 › [DeviceOperation] User config size: 32704
17:00:37.160 › [UhkHidDevice] Available devices unchanged
17:00:37.212 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
17:00:38.219 › [DeviceOperation] ValidatedUserConfig from eeprom error Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHK.AgzSPB1L/resources/app.asar/electron-main.js:2:1299012)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHK.AgzSPB1L/resources/app.asar/electron-main.js:2:1364255)
17:00:38.226 › [UhkHidDevice] Device communication closing.
17:00:38.227 › [UhkHidDevice] Device communication closed.
17:00:38.228 › [UhkHidDevice] Device communication closing.
```

**Comment by mondalaci** [comment] 2022-08-07 21:46
@ert78gb Any ideas?

**Comment by ert78gb** [comment] 2022-08-08 19:32
Hi @enewbury,

Looks like the keyboard/firmware can't serialise the user configuration.
If the keyboard can't parse the user configuration then the LED display shows `FTY` text.

We know about only 1 use case when it could happen
-  the firmware was downgraded to an older version.

Have you done the above described use case?

Please run the `./UHK.Agent-1.5.17-linux-x86_64.AppImage --log=all` command. It will log every USB command and user configuration too. I need these extra information for further investigation.
You can send the log to me directly if you would not like to share here.

**Comment by enewbury** [comment] 2022-08-08 19:37
Nope, I just plugged in the keyboard brand new and opened the agent, and this was the behavior.  Didn't do anything to the firmware.

Full logs below
```
15:35:01.624 › [Electron Main] init services.
15:35:01.626 › [Electron Main] packagesDir: /tmp/.mount_UHKAgexdNcF2/resources
15:35:01.809 › [Electron Main] Create new window.
15:35:01.809 › [WindowState] load settings
15:35:01.810 › [WindowState] loaded settings {
  x: 0,
  y: 507,
  width: 1024,
  height: 933,
  isMaximized: true,
  isFullScreen: false
}
15:35:01.811 › [WindowState] loaded settings is visible true
15:35:01.812 › [WindowState] return with loaded settings
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[31949:0808/153501.931004:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
15:35:01.992 › [DeviceService] init success
15:35:01.994 › [AppUpdateService] init success
15:35:01.994 › [AppService] init success
15:35:01.994 › [SudoService] App root dir:  /tmp/.mount_UHKAgexdNcF2/resources
15:35:02.036 › [WindowState] load settings
15:35:02.037 › [WindowState] loaded settings {
  x: 0,
  y: 507,
  width: 1024,
  height: 933,
  isMaximized: true,
  isFullScreen: false
}
15:35:02.037 › [WindowState] loaded settings is visible true
15:35:02.037 › [WindowState] return with loaded settings
15:35:02.038 › [WindowState] save settings: {
  x: 0,
  y: 507,
  width: 1024,
  height: 933,
  isMaximized: true,
  isFullScreen: false
}
15:35:02.041 › [WindowState] save settings success
15:35:02.053 › [DeviceService] Udev info: Ok
15:35:02.336 › [AppService] get-config: application-settings
15:35:02.337 › [AppService] get-config of "application-settings": undefined
15:35:02.512 › [AppRendererService] init success 
15:35:02.545 › [DeviceRendererService] init success 
15:35:02.548 › Renderer appStart effect start
15:35:02.548 › [AppRendererService] getAppStartInfo
15:35:02.549 › [AppService] getAppStartInfo
15:35:02.548 › Renderer appStart effect end
15:35:02.550 › [AppService] get-config: application-settings
15:35:02.551 › [AppService] getAppStartInfo response: {
  commandLineArgs: { modules: false, log: 'all' },
  platform: 'linux',
  osVersion: '5.18.16-200.fc36.x86_64',
  udevFileContent: '# Ultimate Hacking Keyboard rules\n' +
    '# These are the udev rules for accessing the USB interfaces of the UHK as non-root users.\n' +
    '# Copy this file to /etc/udev/rules.d and physically reconnect the UHK afterwards.\n' +
    'SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"\n' +
    'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n' +
    'KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n'
}
15:35:02.553 › [AppUpdateService] check for update at startup: { checkForUpdateOnStartUp: true }
15:35:02.554 › [AppUpdateService] app started. Automatically check for update.
15:35:02.554 › Checking for update
15:35:02.554 › [AppUpdateService] checking for update
15:35:02.554 › sendIpcToWindow: checking-for-update null
15:35:02.559 › [AppService] get-config of "application-settings": undefined
15:35:02.697 › [AppRendererService] dispatch action: [app] process start info
15:35:02.698 › [AppEffect][processStartInfo] payload: {
  commandLineArgs: { modules: false, log: 'all' },
  platform: 'linux',
  osVersion: '5.18.16-200.fc36.x86_64',
  udevFileContent: '# Ultimate Hacking Keyboard rules\n' +
    '# These are the udev rules for accessing the USB interfaces of the UHK as non-root users.\n' +
    '# Copy this file to /etc/udev/rules.d and physically reconnect the UHK afterwards.\n' +
    'SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"\n' +
    'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n' +
    'KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n'
}
15:35:02.699 › [DeviceService] start poll UHK Device
15:35:02.768 › [UhkHidDevice] Devices before checking permission:
15:35:02.773 › [UhkHidDevice] Available devices changed.
15:35:02.773 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
15:35:02.773 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw3","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":1,"usagePage":1,"usage":6}
15:35:02.773 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw5","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":2,"usagePage":12,"usage":1}
15:35:02.774 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":3,"usagePage":1,"usage":128}
15:35:02.843 › [UhkHidDevice] Available devices unchanged
15:35:02.895 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
15:35:02.896 › [UhkHidDevice] USB[W]: 09 
15:35:02.899 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:02.901 › [UhkHidDevice] USB[W]: 09 
15:35:02.906 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:02.907 › [DeviceOperation] USB[T]: Read right module version information
15:35:02.908 › [UhkHidDevice] USB[W]: 00 01 
15:35:02.911 › [UhkHidDevice] USB[R]: 00 08 00 0a 00 0c 00 04 00 07 00 01 00 04 00 01 00 00 00 04 00 02 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:02.916 › [UhkHidDevice] USB[W]: 09 
15:35:02.924 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:02.925 › [DeviceOperation] Read "leftHalf" version information
15:35:02.925 › [DeviceOperation] USB[T]: Read module version information
15:35:02.925 › [UhkHidDevice] USB[W]: 0e 01 00 
15:35:02.927 › [UhkHidDevice] USB[R]: 00 01 04 00 01 00 00 00 08 00 0a 00 0c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:02.927 › [DeviceService] Device connection state changed to: {
  bootloaderActive: false,
  zeroInterfaceAvailable: true,
  hasPermission: true,
  halvesInfo: {
    areHalvesMerged: true,
    isLeftHalfConnected: true,
    leftModuleSlot: 0,
    rightModuleSlot: 0
  },
  hardwareModules: {
    moduleInfos: [ '[object]' ],
    rightModuleInfo: {
      firmwareVersion: '8.10.12',
      deviceProtocolVersion: '4.7.1',
      moduleProtocolVersion: '4.1.0',
      userConfigVersion: '4.2.0',
      hardwareConfigVersion: '1.0.0'
    }
  },
  multiDevice: false,
  connectedDevice: {
    id: 2,
    name: 'UHK 60 v2',
    vendorId: 7504,
    keyboardPid: 24868,
    bootloaderPid: 24867,
    buspalPid: 24865
  }
}
15:35:02.928 › [DeviceRendererService] dispatch action [device] connection state changed
15:35:02.934 › [DeviceService] stop poll UHK Device
15:35:02.934 › [DeviceService] stopped poll UHK Device
15:35:02.934 › [UhkHidDevice] USB[W]: 00 02 
15:35:02.938 › [UhkHidDevice] USB[R]: 00 40 00 c0 7f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:02.938 › [UhkHidDevice] Device communication closing.
15:35:02.938 › [UhkHidDevice] Device communication closed.
15:35:02.939 › [DeviceService] start poll UHK Device
15:35:02.939 › [DeviceService] stop poll UHK Device
15:35:02.939 › [DeviceService] stopped poll UHK Device
15:35:02.944 › [UhkHidDevice] Available devices unchanged
15:35:02.996 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
15:35:02.997 › [UhkHidDevice] USB[W]: 09 
15:35:02.949 › [DeviceRendererService] dispatch action [device] Read config sizes reply
15:35:03.003 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:03.004 › [UhkHidDevice] USB[W]: 09 
15:35:03.007 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:03.008 › [DeviceOperation] USB[T]: Read ValidatedUserConfig size from keyboard
15:35:03.008 › [UhkHidDevice] USB[W]: 00 02 
15:35:03.011 › [UhkHidDevice] USB[R]: 00 40 00 c0 7f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:03.011 › [UhkHidDevice] Device communication closing.
15:35:03.013 › [UhkHidDevice] Device communication closed.
15:35:03.013 › [DeviceOperation] User config size: 32704
15:35:03.013 › [DeviceOperation] getConfigSize() configSize: 32704
15:35:03.013 › [DeviceOperation] USB[T]: Read ValidatedUserConfig from keyboard
15:35:03.017 › [UhkHidDevice] Available devices unchanged
15:35:03.070 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
15:35:03.071 › [UhkHidDevice] USB[W]: 04 02 3f 00 00 
15:35:04.075 › [UhkHidDevice] USB[R]: 
15:35:04.076 › [DeviceOperation] ValidatedUserConfig from eeprom error Error: Communications error with UHK. Response code: undefined
    at t.UhkHidDevice.<anonymous> (/tmp/.mount_UHKAgexdNcF2/resources/app.asar/electron-main.js:2:1299012)
    at Generator.next (<anonymous>)
    at s (/tmp/.mount_UHKAgexdNcF2/resources/app.asar/electron-main.js:2:1364255)
15:35:04.083 › [UhkHidDevice] Device communication closing.
15:35:04.085 › [UhkHidDevice] Device communication closed.
15:35:04.085 › [UhkHidDevice] Device communication closing.
15:35:04.086 › [DeviceService] start poll UHK Device
15:35:04.105 › [UhkHidDevice] Available devices unchanged
15:35:04.157 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw1","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
15:35:04.158 › [UhkHidDevice] USB[W]: 09 
15:35:04.087 › [DeviceRendererService] dispatch action [user-config] Load User Config from Device reply
15:35:04.160 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:04.356 › Update for version 1.5.17 is not available (latest version: 1.5.17, downgrade is disallowed).
15:35:04.357 › [AppUpdateService] checkForUpdate success
15:35:04.426 › [UhkHidDevice] USB[W]: 09 
15:35:04.429 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:04.695 › [UhkHidDevice] USB[W]: 09 
15:35:04.698 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
15:35:04.965 › [UhkHidDevice] USB[W]: 09 
15:35:04.968 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
...
```

**Comment by mondalaci** [comment] 2022-08-08 19:38
@enewbury Can you reproduce the issue on another computer?

**Comment by enewbury** [comment] 2022-08-08 19:39
I can try spinning up ubuntu in a VM and give it a go. It works on MAC OS

**Comment by mondalaci** [comment] 2022-08-08 19:41
This must be an installation-specific issue then because we haven't received any such reports so far.

**Comment by enewbury** [comment] 2022-08-08 20:11
The agent can't find the keyboard at all from a VM probably because it's some kind of virtual keyboard. Going to try to install ubuntu on a physical machine a bit later to see.

**Comment by mondalaci** [comment] 2022-08-08 20:20
We can't guarantee that Agent works from a VM because it can mess up USB communication. I'm closing this issue but feel free to follow up.

**Closed by mondalaci** 2022-08-08 20:20 UTC

**Comment by enewbury** [comment] 2022-08-08 20:25
Well, I was only using the VM to test it on a different machine. The issue is on my main Fedora workstation.

**Comment by mondalaci** [comment] 2022-08-08 20:29
Then the root cause is something different. Do you possibly connect your UHK via a USB hub, docking station, or KVM switch? If so, please connect it directly.

**Comment by enewbury** [comment] 2022-08-08 20:30
Connected directly and still seeing the issue

**Comment by enewbury** [comment] 2022-08-08 20:32
scratch that, rebooted the program, and now it works... so I just need to connect directly whenever I make configuration changes

**Comment by mondalaci** [comment] 2022-08-08 20:34
Wasn't your UHK connected directly before?

**Comment by enewbury** [comment] 2022-08-08 20:35
I thought I had tried that before, but hadn't rebooted. But no, in general I run it off a CalDigit TS3 thunderbolt hub
