### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by pshirshov** [UltimateHackingKeyboard/agent#1360] opened 2020-10-13 20:12 UTC
While the Agent is nice it's all white and that makes some visually impaired users very uncomfortable.

There are standard dark modes supported by MacOS and Windows and there are standard CSS selectors which should be  available through electron. 

It would be great if you introduce dark mode support. And it should be relatively easy.

**Comment by pshirshov** [comment] 2020-10-13 20:23
Related: https://github.com/UltimateHackingKeyboard/agent/issues/1205

**Comment by mondalaci** [comment] 2020-10-13 20:26
I'm closing this as a duplicate of #1205. Please continue the discussion there, and feel free to reference the suggested low-effort solution.

**Comment by pshirshov** [comment] 2020-10-13 20:31
I don't think that it's fair to just close real issues, especially those which may affect many people, without any resolution. 

And I kinda dislike the idea of a discussion in a closed&abandoned topic.

While I like the hardware, I'm not sure if that's the best way to treat paying customers.

**Comment by mondalaci** [comment] 2020-10-13 20:40
@pshirshov According to the feedback we have been receiving, dark mode is not a widely requested feature despite its mainstream popularity.

If we added dark mode, whenever we introduce a new UI component, we would have to make it compatible with dark mode, so adding dark mode looks like a considerable long-term maintenance burden.

You're saying that dark mode should be relatively easy. I'm open to implementing dark mode if you're suggesting easy ways to do it.

**Comment by pshirshov** [comment] 2020-10-13 20:49
That's not about mainstream popularity. It's about visually impaired users who have strong vitreous degeneration and who cannot look at white interfaces without physical pain.

I guess you would only understand me in case you get into the same trouble.

**Comment by pshirshov** [comment] 2020-10-13 20:55
E.g. you may just combine this: https://dev.to/pqina/poor-man-s-dark-mode-using-css-filter-211n with this: https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme

It won't be beautiful but people like me don't care.

**Comment by tyler-ham** [comment] 2020-10-13 21:23
As a web developer, it is not uncommon for me to spend a disproportionate amount of time improving accessibility. I've never viewed that as a burden, even though the efforts only improve usability for a minority of users. I came across this issue and just wanted to write a note advocating in favor of improving accessibility.

@mondalaci, you didn't address whether you would accept a PR from @dougleville in #1205. The fact that community members are offering to do the work suggests that there would not be a maintenance burden. If you introduce a new UI element in the future that doesn't appear properly in dark mode, a community member could certainly step in at that point with another PR to fix the issue.

I understand you may also be concerned about publishing new releases with known issues, like new UI elements that haven't specifically been adapted for Dark Mode. However, I believe this could also be addressed. For example, on whatever UI element is used to toggle Dark Mode, you could include an "experimental" label. Users might be a little more understanding if they find that certain UI elements have not been updated for Dark Mode yet. And in the meantime, the users who need it or even just have a preference for it would likely be served well 99% of the time.

I just wanted to encourage you to be more accepting of community contributions, even if they may not be needed or requested by a majority of users, and don't let perfection be the enemy of good.

**Comment by mondalaci** [comment] 2020-10-14 09:40
Thanks everyone for weighing in, especially @pshirshov who made me see the value of this feature and offered an easy-to-implement solution. We'll give it a shot, and add a new "Dark mode" checkbox under Agent settings.

**Comment by pshirshov** [comment] 2020-10-14 12:26
Thanks, looking forward for an update!

**Comment by laxu** [comment] 2020-10-16 18:34
Would love to see a dark mode on this as I use it on most apps already. @mondalaci If you need help with it I could look into making one as I finally have some free time. I have a bit of a personal interest in this as I use and prefer dark mode wherever I can.

**Comment by mondalaci** [comment] 2020-10-16 19:02
@laxu Your contribution is most welcome! I've just inverted the colors in Gimp, and it looks reasonably well for what it is:

![image](https://user-images.githubusercontent.com/300402/96298460-c0700080-0ff2-11eb-8db4-e66d44aa2c6f.png)

**Comment by mondalaci** [comment] 2020-10-16 19:03
Of course, doing it the proper way would look much better.

**Comment by laxu** [comment] 2020-10-16 19:06
Alright, I will take a stab at it during the weekend!

**Comment by pshirshov** [comment] 2020-10-18 19:58
To be honest it looks nearly perfect. It would be great to make the keyboard picture less bright with another selector (or just turn off the inversion for it), but apart from that it looks awesome.

**Comment by laxu** [comment] 2020-10-25 22:12
Making good progress with this, have been working on it on and off the past week. Most of the styling is done with only some small things that still need to be styled for the dark theme. 

Still figuring out the best way to make the app choose the dark theme as it relies on Bootstrap having its colours overridden at compile time so my current solution is most likely figuring out how to dynamically load different stylesheets based on what the user prefers.

I have upgraded the app to from Bootstrap 3.x.x to Bootstrap 4.5.3 because overriding every single color manually was too much of a chore. Upgrading to Bootstrap 4 was in order anyway as some of the components like ng-bootstrap have Bootstrap 4.5.x as a dependency and now we can properly theme the app too.

I have created light and dark themes based on the UHK website colors. These are easy to fine tune later if needed.

![image](https://user-images.githubusercontent.com/987972/97120486-f3677200-171f-11eb-92a8-1d87c077e57d.png)

![image](https://user-images.githubusercontent.com/987972/97120321-e5652180-171e-11eb-8ac7-d2ec1d98393b.png)

**Comment by mondalaci** [comment] 2020-10-26 09:53
Thank you for the update!

I'm a bit afraid of the Bootstrap upgrade, as it may break a lot of things. Please create a PR, and make commits in it so that I can provide rapid feedback.

Buttons shouldn't be red, only for critical operations. Please let's stick to the already existing colors as much as possible.

**Comment by laxu** [comment] 2020-10-26 13:02
From my testing Bootstrap upgrade after all the fixes I have done to it does not break anything, it mainly required renaming some classes as they have changed naming from 3 -> 4 and tweaking some styles. Tested both in browser as well as in Electron. All the work is in styles and templates so there is no actual functionality that will break. We were already using the latest ng-bootstrap version which is supposed to use Bootstrap 4.5.x for both components and styles.

On Bootstrap 3 the UHK Agent app just seemed to use the default colors. Bootstrap 4 defaults are brighter so I felt giving it some custom theme colors and thus a bit more identity would be a good idea. I went with the UHK website as basis since there is no color guide.

I feel we should choose some other primary color for dark mode than the blue one used previously for light mode, I felt the red looked overall better but acknowledge that it does blur the line between critical ops. But since these are now very configurable it's not a big deal to change system wide and can be configured separately for either light or dark theme.

Open to suggestions.

**Comment by mondalaci** [comment] 2020-10-26 15:51
Thanks for the detailed update. It gives me peace of mind.

I'm fine with colors of different shades, but red should only be used for critical operations. I wouldn't use UHK website colors for Agent and would rather stick with Bootstrap default colors as much as possible.

Feel free to make a PR any time, and I'll comment further.

**Comment by ert78gb** [comment] 2020-11-08 20:38
@laxu please use css variables for light and dark colours and we will attach `dark-mode` css selector to the `body`. It will dynamically change the colours. Very simple example https://codepen.io/ert78gb/pen/yLJReZL

**Comment by ert78gb** [comment] 2020-11-08 20:43
And just 1 recommendation I like to do 1 thing at 1 step. I mean if you think Boostrap 3 must be upgraded to 4, do the migration in 1 PR and the dark mode feature in another one.
Much easier to review and test, accept and merge.
The colour "discussion" would not block the upgrade merge.

**Comment by laxu** [comment] 2020-11-09 18:51
@ert78gb Already using CSS variables, seemed to be the only smart way to handle it with the dynamic loading of styles in Angular components.

I just figured out how to compile each theme separately and load them based on media queries. Now it even changes the theme if you change the OS setting while you have the app running. This is how it currently works:

1. Stop injecting the main styles in `angular.json`, instead make separate bundles for light and dark themes. The main difference in these files is a single SCSS variable `$dark-theme` which determines which theme's colors are in use.
1. Load light theme as fallback in `index.html` and assign it the ID `uhk-theme`.
1. Use new service ThemeService to check for the `prefers-color-scheme: dark` media query. This also attaches an event listener for changing theme on the fly if you change the OS setting.
1. If media query matches and current theme does not match desired one, replace stylesheet element with new theme. 

Unfortunately separating BS4 upgrade from all the rest is most likely not going to happen, just too many changes here and there that was needed to make this happen so separating them would be quite an ordeal. Looking through my commits the BS4 part should not be very difficult to review because it's mostly just some HTML classes renamed and style tweaks. It's just mixed up with a lot of the CSS vars etc.

JS code is not affected by BS4 upgrade as it was already using latest NG Bootstrap based on BS 4.5.

As for colors, they are now the default ones for light theme and for dark theme I have selected a cyan primary color because it was far better visible than the default blue against a dark background. This will be easy to finetune from a single variable.

I'll try to make a PR soon so you can check it out.

**Comment by ert78gb** [comment] 2020-11-09 19:21
Honestly, I don't understand what is the benefit of the separated bundles. I hope I will understand it from the PR :)

**Closed** 2020-11-17 17:17 UTC

**Comment by pshirshov** [comment] 2020-11-27 14:55
Thank you!

**Comment by krokofant** [comment] 2021-01-27 07:18
The dark theme looks wonderful! Great job!
