### ISSUE TITLE
Can't use scripts in packages/usb

### ISSUE THREAD

**Issue by VinceG3** [UltimateHackingKeyboard/agent#1078] opened 2019-10-23 12:15 UTC
Hi, trying to script my UHK from the command line, use case is automagically syncing config across my 3(!) keyboards. Managed to get remote keymap switching working somehow, but that was a long time ago. Issue is cloning this repository, running `npm i` then trying to execute any scripts in `packages/usb/` directly fails with `Error: Cannot find module 'uhk-common'`.

At first I thought this was something to do with lerna, bear in mind my primary stack isn't nodejs. The symlinking is working fine though, I think the issue has to do with the use of typescript for `uhk-common`. If I add a `index.js` file to `packages/uhk-common` then it will load a blank module. Does typescript need to be a dependency of the `usb` module? I couldn't find anything on how to get nodejs to load a typescript module in the short time I had to dig. How are the scripts in `packages/usb` intended to be run?

Tangentially, I discovered when perusing the lerna issues page that the maintainer repeatedly states that lerna's use case is specifically for easing the maintenance of npm packages and there's no point in using it over relative requires otherwise. As this project does not appear to intend to maintain npm packages, lerna seems to add unneeded complexity to this particular project. Just fyi.

This is important enough to me to spend more time on, but for now I need to get to work. Thanks for making UHK!

**Comment by mondalaci** [comment] 2019-10-23 17:01
First up, thanks for your great support!

The use of lerna is justified as Agent has a separate web and desktop build.

This is issue a duplicate of #891. I'm closing this one, but will prioritize the other one real quick.

**Closed by mondalaci** 2019-10-23 17:01 UTC

**Comment by VinceG3** [comment] 2019-10-23 17:59
Oh, guess I didn't look as carefully as I'd thought for this issue. I'll put some more work into it tonight, I'm sure I can find a solution. If so expect a PR.
