### ISSUE TITLE
Support for inverted scroll direction

### ISSUE THREAD

**Issue by danpalmer** [UltimateHackingKeyboard/agent#1811] opened 2022-07-27 10:17 UTC
On macOS, scrolling is inverted to provide "natural scrolling". It would be great to have an option for this in the scrolling configuration.

**Comment by mondalaci** [comment] 2022-07-27 13:12
Duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/351. Will be included in the next firmware and Agent release.

**Closed by mondalaci** 2022-07-27 13:12 UTC
