### ISSUE TITLE
Constant syslog hammering

### ISSUE THREAD

**Issue by vg250156** [UltimateHackingKeyboard/agent#1275] opened 2020-06-25 01:58 UTC
Not sure if this is the best place to put this, but my UHK is generating constant events to syslog, here is an excerpt:

```
Jun 24 00:09:39 bedroom org.gnome.Nautilus[14370]: 00:09:39.975 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:40 bedroom org.gnome.Nautilus[14370]: 00:09:40.228 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:40 bedroom org.gnome.Nautilus[14370]: 00:09:40.231 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:40 bedroom org.gnome.Nautilus[14370]: 00:09:40.484 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:40 bedroom org.gnome.Nautilus[14370]: 00:09:40.487 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:40 bedroom org.gnome.Nautilus[14370]: 00:09:40.740 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:40 bedroom org.gnome.Nautilus[14370]: 00:09:40.743 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:41 bedroom org.gnome.Nautilus[14370]: 00:09:41.007 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:41 bedroom org.gnome.Nautilus[14370]: 00:09:41.011 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:41 bedroom org.gnome.Nautilus[14370]: 00:09:41.276 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:41 bedroom org.gnome.Nautilus[14370]: 00:09:41.279 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:41 bedroom org.gnome.Nautilus[14370]: 00:09:41.543 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:41 bedroom org.gnome.Nautilus[14370]: 00:09:41.547 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:41 bedroom org.gnome.Nautilus[14370]: 00:09:41.813 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:41 bedroom org.gnome.Nautilus[14370]: 00:09:41.819 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:42 bedroom org.gnome.Nautilus[14370]: 00:09:42.084 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:42 bedroom org.gnome.Nautilus[14370]: 00:09:42.087 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:42 bedroom org.gnome.Nautilus[14370]: 00:09:42.356 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:42 bedroom org.gnome.Nautilus[14370]: 00:09:42.360 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:42 bedroom org.gnome.Nautilus[14370]: 00:09:42.616 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:42 bedroom org.gnome.Nautilus[14370]: 00:09:42.619 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:42 bedroom org.gnome.Nautilus[14370]: 00:09:42.877 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:42 bedroom org.gnome.Nautilus[14370]: 00:09:42.879 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Jun 24 00:09:43 bedroom org.gnome.Nautilus[14370]: 00:09:43.142 › [UhkHidDevice] USB[W]: 09
Jun 24 00:09:43 bedroom org.gnome.Nautilus[14370]: 00:09:43.147 › [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

Any way to squelch this?

**Comment by mondalaci** [comment] 2020-06-25 09:10
This hasn't ever been reported yet, I cannot reproduce it, and your log settings are most likely the culprit.

1. Which Linux distribution and distribution version?
2. Can you reproduce it with the latest Agent version?

**Comment by mondalaci** [comment] 2020-06-25 18:56
Just talked with @ert78gb, and we agreed that this must be an installation-specific issue given that Agent only logs to the `~/.config/uhk-agent/logs/uhk-agent.log` file.

I'm closing this issue, but feel free to follow up, and we'll try to help you.

**Closed by mondalaci** 2020-06-25 18:56 UTC
