### ISSUE TITLE
Unusable on Linux when touchpad is attached

### ISSUE THREAD

**Issue by mroach** [UltimateHackingKeyboard/agent#1807] opened 2022-07-11 07:34 UTC
I just got my UHK V2 with the touchpad module. When opening the agent, it appears as though thouchpad is "pulsing", as if it's wanting attention. I realise what's actually happening is the agent thinks the touchpad is constantly being disconnection and re-connected. As a consequence, any customisation window you have open is closed as soon as the state changes, making the app unusable unless I remove the touchpad. Then of course I can't configure the touchpad.

I'm running version 1.5.17 of the agent on Fedora 36.

Here's a full output log of running the agent. You'll notice once the app starts, this bit starts repeating rapidly:

```
09:29:58.759 › [DeviceRendererService] dispatch action [device] connection state changed
09:29:59.037 › [DeviceOperation] Read "leftHalf" version information
09:29:59.041 › [DeviceService] Device connection state changed to: {
```

Full log of opening the app and leaving it open for a few seconds:

```
09:29:54.145 › [Electron Main] init services.
09:29:54.148 › [Electron Main] packagesDir: /tmp/.mount_UHK.Ag1uYKhw/resources
09:29:54.338 › [Electron Main] Create new window.
09:29:54.339 › [WindowState] load settings
09:29:54.340 › [WindowState] loaded settings {
  x: 3074,
  y: 77,
  width: 1014,
  height: 1643,
  isMaximized: false,
  isFullScreen: false
}
09:29:54.341 › [WindowState] loaded settings is visible true
09:29:54.341 › [WindowState] return with loaded settings
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[277452:0711/092954.466804:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
09:29:54.526 › [DeviceService] init success
09:29:54.528 › [AppUpdateService] init success
09:29:54.528 › [AppService] init success
09:29:54.529 › [SudoService] App root dir:  /tmp/.mount_UHK.Ag1uYKhw/resources
09:29:54.587 › [DeviceService] Udev info: Ok
09:29:54.849 › [AppService] get-config: application-settings
09:29:54.850 › [AppService] get-config of "application-settings": {"checkForUpdateOnStartUp":true,"everAttemptedSavingToKeyboard":true,"animationEnabled":true,"appTheme":"system"}
09:29:55.027 › [AppRendererService] init success 
09:29:55.060 › [DeviceRendererService] init success 
09:29:55.063 › Renderer appStart effect start
09:29:55.063 › [AppRendererService] getAppStartInfo
09:29:55.064 › [AppService] getAppStartInfo
09:29:55.063 › Renderer appStart effect end
09:29:55.065 › [AppService] get-config: application-settings
09:29:55.065 › [AppService] getAppStartInfo response: {
  commandLineArgs: { modules: false },
  platform: 'linux',
  osVersion: '5.18.9-200.fc36.x86_64',
  udevFileContent: '# Ultimate Hacking Keyboard rules\n' +
    '# These are the udev rules for accessing the USB interfaces of the UHK as non-root users.\n' +
    '# Copy this file to /etc/udev/rules.d and physically reconnect the UHK afterwards.\n' +
    'SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"\n' +
    'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n' +
    'KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n'
}
09:29:55.066 › [AppUpdateService] check for update at startup: { checkForUpdateOnStartUp: true }
09:29:55.067 › [AppUpdateService] app started. Automatically check for update.
09:29:55.067 › Checking for update
09:29:55.067 › [AppUpdateService] checking for update
09:29:55.067 › sendIpcToWindow: checking-for-update null
09:29:55.074 › [AppService] get-config of "application-settings": {"checkForUpdateOnStartUp":true,"everAttemptedSavingToKeyboard":true,"animationEnabled":true,"appTheme":"system"}
09:29:55.224 › [WindowState] save settings: {
  x: 3072,
  y: 85,
  width: 1024,
  height: 1643,
  isMaximized: false,
  isFullScreen: false
}
09:29:55.238 › [WindowState] save settings success
09:29:55.229 › [AppRendererService] dispatch action: [app] process start info
09:29:55.230 › [AppEffect][processStartInfo] payload: {
  commandLineArgs: { modules: false },
  platform: 'linux',
  osVersion: '5.18.9-200.fc36.x86_64',
  udevFileContent: '# Ultimate Hacking Keyboard rules\n' +
    '# These are the udev rules for accessing the USB interfaces of the UHK as non-root users.\n' +
    '# Copy this file to /etc/udev/rules.d and physically reconnect the UHK afterwards.\n' +
    'SUBSYSTEM=="input", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", GROUP="input", MODE="0660"\n' +
    'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n' +
    'KERNEL=="hidraw*", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="612[0-7]", TAG+="uaccess"\n'
}
09:29:55.240 › [DeviceService] start poll UHK Device
09:29:55.275 › [WindowState] save settings: {
  x: 3074,
  y: 77,
  width: 1014,
  height: 1643,
  isMaximized: false,
  isFullScreen: false
}
09:29:55.277 › [WindowState] save settings success
09:29:55.277 › [WindowState] save settings: {
  x: 3074,
  y: 77,
  width: 1014,
  height: 1643,
  isMaximized: false,
  isFullScreen: false
}
09:29:55.279 › [WindowState] save settings success
09:29:55.291 › [UhkHidDevice] Devices before checking permission:
09:29:55.294 › [UhkHidDevice] Available devices changed.
09:29:55.294 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
09:29:55.294 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw7","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":1,"usagePage":1,"usage":6}
09:29:55.294 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw8","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":2,"usagePage":12,"usage":1}
09:29:55.294 › [UhkHidDevice] Added: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw9","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":3,"usagePage":1,"usage":128}
09:29:55.365 › [UhkHidDevice] Available devices unchanged
09:29:55.417 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
09:29:55.438 › [DeviceOperation] Read "leftHalf" version information
09:29:55.441 › [DeviceOperation] Read "rightModule" version information
09:29:55.445 › [DeviceService] Device connection state changed to: {
  bootloaderActive: false,
  zeroInterfaceAvailable: true,
  hasPermission: true,
  halvesInfo: {
    areHalvesMerged: false,
    isLeftHalfConnected: true,
    leftModuleSlot: 0,
    rightModuleSlot: 5
  },
  hardwareModules: {
    moduleInfos: [ '[object]', '[object]' ],
    rightModuleInfo: {
      firmwareVersion: '8.10.12',
      deviceProtocolVersion: '4.7.1',
      moduleProtocolVersion: '4.1.0',
      userConfigVersion: '4.2.0',
      hardwareConfigVersion: '1.0.0'
    }
  },
  multiDevice: false,
  connectedDevice: {
    id: 2,
    name: 'UHK 60 v2',
    vendorId: 7504,
    keyboardPid: 24868,
    bootloaderPid: 24867,
    buspalPid: 24865
  }
}
09:29:55.445 › [DeviceRendererService] dispatch action [device] connection state changed
09:29:55.452 › [DeviceService] stop poll UHK Device
09:29:55.453 › [DeviceService] stopped poll UHK Device
09:29:55.455 › [UhkHidDevice] Device communication closing.
09:29:55.458 › [UhkHidDevice] Device communication closed.
09:29:55.458 › [DeviceService] start poll UHK Device
09:29:55.458 › [DeviceService] stop poll UHK Device
09:29:55.458 › [DeviceService] stopped poll UHK Device
09:29:55.462 › [UhkHidDevice] Available devices unchanged
09:29:55.513 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
09:29:55.469 › [DeviceRendererService] dispatch action [device] Read config sizes reply
09:29:55.537 › [UhkHidDevice] Device communication closing.
09:29:55.540 › [UhkHidDevice] Device communication closed.
09:29:55.540 › [DeviceOperation] User config size: 32704
09:29:55.543 › [UhkHidDevice] Available devices unchanged
09:29:55.596 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
09:29:55.600 › [DeviceOperation] userConfigSize: 3978
09:29:55.769 › [UhkHidDevice] Device communication closing.
09:29:55.771 › [UhkHidDevice] Device communication closed.
09:29:55.772 › [DeviceOperation] Hardware config size: 64
09:29:55.775 › [UhkHidDevice] Available devices unchanged
09:29:55.826 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
09:29:55.833 › [UhkHidDevice] Device communication closing.
09:29:55.836 › [UhkHidDevice] Device communication closed.
09:29:55.845 › [UhkHidDevice] Available devices unchanged
09:29:55.898 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
09:29:55.910 › [DeviceOperation] Read "leftHalf" version information
09:29:55.915 › [DeviceOperation] Read "rightModule" version information
09:29:55.926 › [UhkHidDevice] Device communication closing.
09:29:55.929 › [UhkHidDevice] Device communication closed.
09:29:55.929 › [DeviceService] start poll UHK Device
09:29:55.930 › [DeviceRendererService] dispatch action [user-config] Load User Config from Device reply
09:29:55.956 › [UhkHidDevice] Available devices unchanged
09:29:56.008 › [UhkHidDevice] Used device: {"vendorId":"0x1D50","productId":"0x6124","path":"/dev/hidraw6","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK 60 v2","release":258,"interface":0,"usagePage":65280,"usage":1}
09:29:55.972 › [AppEffects] navigate to { commands: [ '/' ] }
09:29:56.288 › [DeviceOperation] Read "leftHalf" version information
09:29:56.291 › [DeviceService] Device connection state changed to: {
  bootloaderActive: false,
  zeroInterfaceAvailable: true,
  hasPermission: true,
  halvesInfo: {
    areHalvesMerged: false,
    isLeftHalfConnected: true,
    leftModuleSlot: 0,
    rightModuleSlot: 0
  },
  hardwareModules: {
    moduleInfos: [ '[object]' ],
    rightModuleInfo: {
      firmwareVersion: '8.10.12',
      deviceProtocolVersion: '4.7.1',
      moduleProtocolVersion: '4.1.0',
      userConfigVersion: '4.2.0',
      hardwareConfigVersion: '1.0.0'
    }
  },
  multiDevice: false,
  connectedDevice: {
    id: 2,
    name: 'UHK 60 v2',
    vendorId: 7504,
    keyboardPid: 24868,
    bootloaderPid: 24867,
    buspalPid: 24865
  }
}
09:29:56.291 › [DeviceRendererService] dispatch action [device] connection state changed
09:29:56.564 › [DeviceOperation] Read "leftHalf" version information
09:29:56.567 › [DeviceOperation] Read "rightModule" version information
09:29:56.570 › [DeviceService] Device connection state changed to: {
  bootloaderActive: false,
  zeroInterfaceAvailable: true,
  hasPermission: true,
  halvesInfo: {
    areHalvesMerged: false,
    isLeftHalfConnected: true,
    leftModuleSlot: 0,
    rightModuleSlot: 5
  },
  hardwareModules: {
    moduleInfos: [ '[object]', '[object]' ],
    rightModuleInfo: {
      firmwareVersion: '8.10.12',
      deviceProtocolVersion: '4.7.1',
      moduleProtocolVersion: '4.1.0',
      userConfigVersion: '4.2.0',
      hardwareConfigVersion: '1.0.0'
    }
  },
  multiDevice: false,
  connectedDevice: {
    id: 2,
    name: 'UHK 60 v2',
    vendorId: 7504,
    keyboardPid: 24868,
    bootloaderPid: 24867,
    buspalPid: 24865
  }
}
09:29:56.571 › [DeviceRendererService] dispatch action [device] connection state changed
09:29:56.839 › Update for version 1.5.17 is not available (latest version: 1.5.17, downgrade is disallowed).
09:29:56.840 › [AppUpdateService] checkForUpdate success
09:29:57.918 › [DeviceOperation] Read "leftHalf" version information
09:29:57.922 › [DeviceService] Device connection state changed to: {
  bootloaderActive: false,
  zeroInterfaceAvailable: true,
  hasPermission: true,
  halvesInfo: {
    areHalvesMerged: false,
    isLeftHalfConnected: true,
    leftModuleSlot: 0,
    rightModuleSlot: 0
  },
  hardwareModules: {
    moduleInfos: [ '[object]' ],
    rightModuleInfo: {
      firmwareVersion: '8.10.12',
      deviceProtocolVersion: '4.7.1',
      moduleProtocolVersion: '4.1.0',
      userConfigVersion: '4.2.0',
      hardwareConfigVersion: '1.0.0'
    }
  },
  multiDevice: false,
  connectedDevice: {
    id: 2,
    name: 'UHK 60 v2',
    vendorId: 7504,
    keyboardPid: 24868,
    bootloaderPid: 24867,
    buspalPid: 24865
  }
}
09:29:57.922 › [DeviceRendererService] dispatch action [device] connection state changed
09:29:58.469 › [DeviceOperation] Read "leftHalf" version information
09:29:58.473 › [DeviceOperation] Read "rightModule" version information
09:29:58.476 › [DeviceService] Device connection state changed to: {
  bootloaderActive: false,
  zeroInterfaceAvailable: true,
  hasPermission: true,
  halvesInfo: {
    areHalvesMerged: false,
    isLeftHalfConnected: true,
    leftModuleSlot: 0,
    rightModuleSlot: 5
  },
  hardwareModules: {
    moduleInfos: [ '[object]', '[object]' ],
    rightModuleInfo: {
      firmwareVersion: '8.10.12',
      deviceProtocolVersion: '4.7.1',
      moduleProtocolVersion: '4.1.0',
      userConfigVersion: '4.2.0',
      hardwareConfigVersion: '1.0.0'
    }
  },
  multiDevice: false,
  connectedDevice: {
    id: 2,
    name: 'UHK 60 v2',
    vendorId: 7504,
    keyboardPid: 24868,
    bootloaderPid: 24867,
    buspalPid: 24865
  }
}
09:29:58.476 › [DeviceRendererService] dispatch action [device] connection state changed
09:29:58.755 › [DeviceOperation] Read "leftHalf" version information
09:29:58.759 › [DeviceService] Device connection state changed to: {
  bootloaderActive: false,
  zeroInterfaceAvailable: true,
  hasPermission: true,
  halvesInfo: {
    areHalvesMerged: false,
    isLeftHalfConnected: true,
    leftModuleSlot: 0,
    rightModuleSlot: 0
  },
  hardwareModules: {
    moduleInfos: [ '[object]' ],
    rightModuleInfo: {
      firmwareVersion: '8.10.12',
      deviceProtocolVersion: '4.7.1',
      moduleProtocolVersion: '4.1.0',
      userConfigVersion: '4.2.0',
      hardwareConfigVersion: '1.0.0'
    }
  },
  multiDevice: false,
  connectedDevice: {
    id: 2,
    name: 'UHK 60 v2',
    vendorId: 7504,
    keyboardPid: 24868,
    bootloaderPid: 24867,
    buspalPid: 24865
  }
}
09:29:58.759 › [DeviceRendererService] dispatch action [device] connection state changed
09:29:59.037 › [DeviceOperation] Read "leftHalf" version information
09:29:59.041 › [DeviceService] Device connection state changed to: {
  bootloaderActive: false,
  zeroInterfaceAvailable: true,
  hasPermission: true,
  halvesInfo: {
    areHalvesMerged: false,
    isLeftHalfConnected: true,
    leftModuleSlot: 0,
    rightModuleSlot: 5
  },
  hardwareModules: {
    moduleInfos: [ '[object]' ],
    rightModuleInfo: {
      firmwareVersion: '8.10.12',
      deviceProtocolVersion: '4.7.1',
      moduleProtocolVersion: '4.1.0',
      userConfigVersion: '4.2.0',
      hardwareConfigVersion: '1.0.0'
    }
  },
  multiDevice: false,
  connectedDevice: {
    id: 2,
    name: 'UHK 60 v2',
    vendorId: 7504,
    keyboardPid: 24868,
    bootloaderPid: 24867,
    buspalPid: 24865
  }
}
09:29:59.041 › [DeviceRendererService] dispatch action [device] connection state changed
09:29:59.067 › [WindowState] save settings: {
  x: 3074,
  y: 77,
  width: 1014,
  height: 1643,
  isMaximized: false,
  isFullScreen: false
}
09:29:59.080 › [WindowState] save settings success
09:29:59.087 › [Electron Main] win closed
09:29:59.088 › [DeviceService] stop poll UHK Device
09:29:59.088 › [DeviceService] stopped poll UHK Device
09:29:59.088 › [DeviceService] Device connection checker stopped.
09:29:59.088 › [UhkHidDevice] Device communication closing.
09:29:59.090 › [UhkHidDevice] Device communication closed.
```

**Comment by mondalaci** [comment] 2022-07-11 08:32
Closing as a duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/364

**Closed by mondalaci** 2022-07-11 08:32 UTC

**Comment by mroach** [comment] 2022-07-11 08:46
Ah. I looked through issues here to find a duplicate but didn't realise it was an issue with firmware and not the agent. Thanks, I'll follow that issue for updates.
