### ISSUE TITLE
Checking keymap status

### ISSUE THREAD

**Issue by NejcZdovc** [UltimateHackingKeyboard/agent#175] opened 2016-11-21 05:22 UTC
When deleting macro, we also need to check if keymap contains macros with deleted macro. 
When deleting keymap, we need to check if any other keymap contains deleted keymap in the switch action.

**Comment by fjozsef** [comment] 2016-11-21 10:07
Duplicate of #140

**Closed by fjozsef** 2016-11-21 10:07 UTC
