### ISSUE TITLE
Wrong parameter name used in smart macro reference in set » mouse key speeds interactive helpers

### ISSUE THREAD

**Issue by michallepicki** [UltimateHackingKeyboard/agent#1871] opened 2022-10-23 19:09 UTC
First of all, thank you for the smart macros, they will be very very appreciated! MacOS and Linux interpret the mouse speeds differently, and I switch between them often

After setting up a two macros using the mouse speed UI helpers, and trying to use them, I got these errors from printStatus:
```
set mouse speeds !: 0: 2: parameter not recognizeD:: move.acceleration 2000

set mouse speeds 2: 0: 2: parameter not recognized:: move.acceleration 1500

```

But the I believe this helper should use `initialAcceleration` instead of `acceleration`:
![image](https://user-images.githubusercontent.com/4972756/197410546-5dc43418-bcaa-437d-9ab8-fa30dc55c657.png)

Another weird issue about this log is ! instead of 1 and D instead of d on the first line (?) But that's just the log

(After fixing this in my macro I was also confused whether this worked at all but I think it works, it's just that the speeds overriden by macros are separate from global speed settings and they are not shown anywhere in the agent?)

That's happening using today's 2.0.0 pre-relase, release page says it's:
```
commit: f188521
Firmware: 9.1.1 | Device Protocol: 4.8.0 | User Config: 5.1.0 | Hardware Config: 1.0.0
```

**Comment by mondalaci** [comment] 2022-10-23 19:21
Glad you appreciate smart macros and thanks for the quick feedback!

Please copy-paste the smart macro commands you're using, followed by the errors triggered by the commands.

**Comment by michallepicki** [comment] 2022-10-23 19:26
Sure! This macro called `set mouse speed 1`, created using UI helpers from reference:
```
set mouseKeys.move.initialSpeed 200
set mouseKeys.move.baseSpeed 1100
set mouseKeys.move.acceleration 2000
set mouseKeys.move.deceleratedSpeed 500
set mouseKeys.move.acceleratedSpeed 3000
```
causes this error:
```
set mouse speeds 1: 0: 2: parameter not recognized;: move.acceleration 2000

```

I fixed this by changing it to:
```
set mouseKeys.move.initialSpeed 200
set mouseKeys.move.baseSpeed 1100
set mouseKeys.move.initialAcceleration 2000
set mouseKeys.move.deceleratedSpeed 500
set mouseKeys.move.acceleratedSpeed 3000
```

I believe the UI helper needs to be fixed to use the correct property name

**Comment by michallepicki** [comment] 2022-10-23 19:35
This is probably at https://github.com/UltimateHackingKeyboard/firmware/blob/a2ad729cec4ee277d4ab899f0e7be6cd7bfa0341/doc/dist/script.mjs#L317 ? But I'm not sure, didn't check thoroughly

**Comment by mondalaci** [comment] 2022-10-23 19:56
@michallepicki You're spot on. Fixed by 47e622d7dd561ee57d2724d60b34302f96dac1de and the fix will be included to the next firmware release.

**Closed by mondalaci** 2022-10-23 19:56 UTC

**Comment by mondalaci** [comment] 2022-10-25 20:10
@kareltucek Although I've resolved the issue, the error messages of the status buffer could be improved. Would you improve them?

**Comment by michallepicki** [comment] 2022-10-26 06:52
@mondalaci do you mean the unexpected `!` and `D` that showed up instead of `1` and `D` in my error message once? I couldn't reproduce this after, maybe I was hitting shift immediately after invoking the macro or something like that. Otherwise I personally think the error message is fine.

**Comment by mondalaci** [comment] 2022-10-26 07:02
@michallepicki Thanks for the clarification!

Now it makes more sense, although I'm unsure what the numbers of `set mouse speeds 2: 0: 2` mean.

In any case, modifiers shouldn't affect the output of the status buffer to avoid misunderstandings.

**Comment by michallepicki** [comment] 2022-10-26 12:38
> Now it makes more sense, although I'm unsure what the numbers of `set mouse speeds 2: 0: 2` mean.

"set mouse speeds 2" was my macro name. I don't know about the other numbers.

**Comment by mondalaci** [comment] 2022-10-31 09:19
@kareltucek What do these numbers mean?

**Comment by kareltucek** [comment] 2022-10-31 13:21
Action index and command address.

(Filled it into reference manual in c5661811fd20539c1ddc8ea7873222418dc3a713 .)

**Comment by kareltucek** [comment] 2022-10-31 13:23
The `!` is caused by the neighbouring `:` - your text editor can't keep up with UHK speed... Maybe we should consider setting default `keystrokeDelay` to 5 or 10 or something. (Although, admittedly I do fear that it may cause other problems - not sure which ones...)

**Comment by mondalaci** [comment] 2022-10-31 15:43
The referenced sha is unlinked for some reason. Would you link the relevant part of the documentation?

Tweaking the output of the status buffer is probably not worth the effort, so let's keep it this way for now.

**Comment by kareltucek** [comment] 2022-10-31 15:59
> The referenced sha is unlinked for some reason. Would you link the relevant part of the documentation?

https://github.com/kareltucek/firmware/commit/c5661811fd20539c1ddc8ea7873222418dc3a713 

(The reason is that it is in my repository.)

**Comment by mondalaci** [comment] 2022-10-31 16:06
What "command address" means exactly?

I'd welcome this addition to the stock repo. What's your strategy for merging changes from your repo to stock?

**Comment by kareltucek** [comment] 2022-10-31 16:28
> What "command address" means exactly?

Please see `ADDRESS` entry in https://github.com/kareltucek/firmware/blob/master/doc-dev/reference-manual.md

> I'd welcome this addition to the stock repo. What's your strategy for merging changes from your repo to stock?

In general, please see Branches section of https://github.com/kareltucek/firmware/blob/master/README.md .

W.r.t. official repository:
- substantial functionality changes in code core (i.e., requested feature requests or bug fixes, or simply changes that significantly affect core functionality code) go into a PRs into uhk/master.
- minor fixes and amends go into common_trunk_upstream, which eventually propagates into uhk/master
- fork (non-core) functionality (mostly extended commands) go into common_trunk_upstream

**Comment by kareltucek** [comment] 2022-10-31 23:12
I am generally already trying not to accumulate stuff on common_trunk*. The trouble is that when I dig into a problem, I often produce many changes in a short time...

**Comment by mondalaci** [comment] 2022-11-01 07:30
What's the rationale of the current scheme? Wouldn't it be easier to commit directly to master, except for larger features/fixes that contain multiple commits?

**Comment by kareltucek** [comment] 2022-11-01 08:29
You mean to uhk/master? 

- It is a custom to have at least one other person see every piece of code that is merged into production branches. Reasons:
  - To make sure that at least one more person has some idea about the structure and content of the code.
  - To make sure that code is readable and understandable. (If it is not, comments or refactors should be requested).
  - It helps in spotting problems. The reviewer may spot a problem that the author does not see. But also, even asking random "officious" questions often makes the author think about the PR from a different perspective, and may make _the author_ spot problems.
  - Just knowing that someone else will be reviewing the code helps to prevent me from dropping code quality.
- I would find it very rude to push into someone else's branches/repositories without being explicitly asked to.

**Comment by kareltucek** [comment] 2022-11-01 09:06
Anyway, do you wish to review the third class? I can change the flow so that every such change is PRd either against common_trunk (preferably) or against uhk/master. (Such PRs would have to be reviewed with high priority - in days, not weeks or months.)

**Comment by mondalaci** [comment] 2022-11-01 11:11
Well-articulated reasons. I prefer small PRs against the official UHK repo as frequently as possible. This way, it's easier to review them. I can review them within days.
