### ISSUE TITLE
Turn off LED in sleep mode

### ISSUE THREAD

**Issue by emin-grbo** [UltimateHackingKeyboard/agent#1939] opened 2022-12-13 20:07 UTC
I saw some mention of this in the blog posts and similar, but it was only mentioned that it MIGHT be added into the Agent.

I never turn off my mac and just put it to sleep, however, keyboard shines quite brightly (which is really cool while i work), but I was wondering i it would be feasible to add a sleep mode light setup? Or a toggle?

Right now I manually turn down all the lights before signing off 🤷‍♂️

I hope I am not missing a simple "already covered" section. I did try to look on the site and in these issues 😅

Cheers! 
p.s. Not sure if I need to sign the CLA and all that if I am submitting a feature request? I can do that if needed.

**Comment by mondalaci** [comment] 2022-12-13 20:14
Closing this issue as a duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/461

Until the referenced issue is fixed, please use the LED fade timeout [smart macro](https://ultimatehackingkeyboard.com/blog/2022/11/18/agent-2-next-level-uhk-and-module-configuration).

No CLA signing is needed for feature requests. :)

**Closed by mondalaci** 2022-12-13 20:14 UTC
