### ISSUE TITLE
Agent build fails on Debian amd64 (Error 404 downloading Node-HID v0.5.4-node-v57)

### ISSUE THREAD

**Issue by TorC8** [UltimateHackingKeyboard/agent#405] opened 2017-09-06 04:00 UTC
I happened to try on a system that has not previously had agent installed.  Node.js version 8.4.0; npm version 5.3.0.

What appears to be the relevant section of error:
lerna ERR! execute node-pre-gyp info check checked for "/home/tor/sourceinstall/agent/packages/uhk-agent/node_modules/node-hid/build/Release/HID.node" (not found)
lerna ERR! execute node-pre-gyp http GET https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz
lerna ERR! execute node-pre-gyp http 404 https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz
lerna ERR! execute node-pre-gyp ERR! Tried to download(404): https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz 
lerna ERR! execute node-pre-gyp ERR! Pre-built binaries not found for node-hid@0.5.4 and node@8.4.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
lerna ERR! execute node-pre-gyp http 404 status code downloading tarball https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v57-linux-x64.tar.gz 
lerna ERR! execute node-pre-gyp verb command build [ 'rebuild' ]
lerna ERR! execute ../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
lerna ERR! execute  #include <libusb.h>
lerna ERR! execute                     ^
lerna ERR! execute compilation terminated.
lerna ERR! execute make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1

Full build log here: [170905install.txt](https://github.com/UltimateHackingKeyboard/agent/files/1279718/170905install.txt)

**Comment by mondalaci** [comment] 2017-09-06 12:35
This build failure was caused by libusb-dev not being installed on the system, but it shouldn't be an issue anymore. I've just merged #404 which gets rid of libusb.

Please fetch the Agent repo and retry. If it fails please open another issue.

**Closed by mondalaci** 2017-09-06 12:35 UTC
