### ISSUE TITLE
UI consistancy between macros and keylayouts?

### ISSUE THREAD

**Issue by firstnevyn** [UltimateHackingKeyboard/agent#1010] opened 2019-08-05 01:10 UTC
This is super low priority but I needed to make a new layout recently and it wasn't obvious to me that I did that by cloning an existing layout to a new layout. a plus button like the one by macros with a little wizard saying "build from std layout or select existing layout" that let you name your new layout and set fn swap for all existing layouts would be nice.

Is it worth having a + beside keylayout like macro.. have it default to a layout with a blank name and qwerty std?

Grant

**Comment by mondalaci** [comment] 2019-08-05 13:36
Thanks for your suggestion, Grant! We plan to proceed as suggested. Closing this issue as it's a duplicate of #459.

**Closed by mondalaci** 2019-08-05 13:36 UTC
