### ISSUE TITLE
Macro delays longer than 10 seconds

### ISSUE THREAD

**Issue by bistabil** [UltimateHackingKeyboard/agent#1867] opened 2022-10-20 10:21 UTC
This is something I am aware of for a long time but I never found time to report it.
When I am trying to add a longer delay inside a macro, if I for example try to set a delay of 100 seconds, it results in 10 seconds being added instead.
I haven't tried to modify configuration file manually to set a delay and import it but there must be a reason this is not available.
Right now I am solving this problem by creating loops with registers or just multiplying the same line over and over.

**Comment by kareltucek** [comment] 2022-10-20 15:48
Confirming, although the actual limit is 65 seconds, not 10. If larger value is entered, it looks like the last digit of its decimal string representation is removed (repeatedly, until the number fits). This happens for the regular native delay action available through standard GUI. The value is clamped when "save" (action) is clicked - right in Agent.

Firmware stores the value in a uint16, so it supports exactly those 65 seconds (2^16-1 = 65535 ms), so the limit is apparently intentional. 

It looks like the limitation is explicitly implemented in Agent, but stems from the serialization format, which does not have functions defined to read numbers higher than 16bits. Theoretically, it could be extended but would require altering all the chain links - the agent, the serialization format (and its serializer and parsers), and the firmware.

Also, it can be workarounded through extended smart macro commands, which should allow 2^31-1 ms. Be warned though: UHK timer is not very precise.

**Comment by kareltucek** [comment] 2022-10-20 15:51
(So my conclusion is that Agent should fix its clamping algorithm to a deterministic `min(enteredValue, 65)`, and otherwise marked as "not a bug" or "won't fix".)

**Comment by mondalaci** [comment] 2022-10-21 07:17
@kareltucek Thanks for the insight!

@bistabil Would 65 seconds be sufficient? If not, what's your use case?

**Comment by bistabil** [comment] 2022-10-24 08:31
I had several use cases but right now I am trying to send a message in the game I am playing every few minutes.
Just found it weird that there were no notifications or something indicating what is the limit and my input was just overridden.
Having it to 60 seconds (1 minute) would maybe be more user-friendly because setting it to 65 would more likely rise some questions in the future :-)

**Comment by mondalaci** [comment] 2022-10-24 09:53
@bistabil Thanks for explaining your use case!

@kareltucek I agree that Agent should max out this value. Longer delays should be very rare, and they can be implemented via `delayUntil` as suggested.

**Closed** 2022-11-13 21:15 UTC
