### ISSUE TITLE
Cannot update firmware on MacBook Pro

### ISSUE THREAD

**Issue by MyDogTom** [UltimateHackingKeyboard/agent#746] opened 2018-08-07 12:20 UTC
Keyboard is connected via usb adapter (since MacBook has only usb type-c).
Current firmware: 8.2.5
Version, that I'm trying to install : 8.4.0 (bundled wit agent)
I tried to connect keyboard to all usb ports one by one. Everything else is disconnected. Result is the same.
 
Output:
```
Start flashing firmware
[14:14:00.081] [UhkHidDevice] Available devices unchanged
[14:14:00.083] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14100000/USB2.0 Hub@14100000/AppleUSB20Hub@14100000/AppleUSB20HubPort@14110000/Ultimate Hacking Keyboard@14110000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14110000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":65280,"usage":1}
[14:14:00.083] [UhkHidDevice] USB[W]: 09 
[14:14:00.090] [UhkHidDevice] USB[R]: 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:14:00.090] [DeviceOperation] USB[T]: Read left module version information
[14:14:00.091] [UhkHidDevice] USB[W]: 0e 01 00 
[14:14:00.098] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:14:00.098] [DeviceOperation] USB[T]: Read right module version information
[14:14:00.098] [UhkHidDevice] USB[W]: 00 01 
[14:14:00.106] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[14:14:00.106] Device right firmware version: 8.2.5
[14:14:00.106] Device left firmware version: 8.2.5
[14:14:00.109] New firmware version: 8.4.0
[14:14:00.110] [UhkOperations] Operating system: Darwin 17.7.0 x64
[14:14:00.110] [UhkOperations] Start flashing right firmware
[14:14:00.111] [UhkHidDevice] Start reenumeration, mode: Bootloader
[14:14:00.227] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[14:14:00.228] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[14:14:00.232] [DeviceService] updateFirmware error { message: 'Cannot write to HID device',
  stack: 'Error: Cannot write to HID device\n    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:184:1)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:4:42)\n    at <anonymous>' }
[14:14:00.233] [UhkHidDevice] USB[W]: 09 
[14:14:00.236] [DeviceService] Read hardware modules information failed Error: Cannot write to HID device
    at Promise (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:109:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.waitUntilKeyboardBusy (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:138:1)
    at DeviceService.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/src/services/device.service.ts:137:31)
    at Generator.next (<anonymous>)

[14:14:00.581] [UhkHidDevice] Transfer error:  Error: could not read from HID device

[14:14:00.581] [UhkHidDevice] Device communication closing.
[14:14:00.582] [UhkHidDevice] Device communication closed.
[14:14:00.748] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
Cannot write to HID device

```

**Comment by mondalaci** [comment] 2018-08-07 13:09
Please link the product page of your USB adapter.

Can you try a different USB adapter / hub / docking station with your UHK?

**Comment by MyDogTom** [comment] 2018-08-08 08:00
Adapter model: A1621
According to Google this one: https://www.apple.com/shop/product/MJ1K2AM/A/usb-c-digital-av-multiport-adapter but I wasn't able to confirm that this is exact the same model.

>Can you try a different USB adapter / hub / docking station with your UHK?

I have another adapter (same model). Update also doesn't work.

I tried update via usb on monitor. No success:
```
Start flashing firmware
[09:57:44.552] [UhkHidDevice] Available devices unchanged
[09:57:44.553] [UhkHidDevice] Used device: {"vendorId":7504,"productId":24866,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/IOUSBHostDevice@14410000/AppleUSB20Hub@14410000/AppleUSB20HubPort@14413000/Ultimate Hacking Keyboard@14413000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14413000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"Ultimate Hacking Keyboard","release":257,"interface":-1,"usagePage":65280,"usage":1}
[09:57:44.553] [UhkHidDevice] USB[W]: 09 
[09:57:44.561] [UhkHidDevice] USB[R]: 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[09:57:44.561] [DeviceOperation] USB[T]: Read left module version information
[09:57:44.561] [UhkHidDevice] USB[W]: 0e 01 00 
[09:57:44.569] [UhkHidDevice] USB[R]: 00 01 04 00 00 00 00 00 08 00 02 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[09:57:44.569] [DeviceOperation] USB[T]: Read right module version information
[09:57:44.569] [UhkHidDevice] USB[W]: 00 01 
[09:57:44.577] [UhkHidDevice] USB[R]: 00 08 00 02 00 05 00 04 00 03 00 01 00 04 00 00 00 00 00 04 00 00 00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
[09:57:44.577] Device right firmware version: 8.2.5
[09:57:44.578] Device left firmware version: 8.2.5
[09:57:44.579] New firmware version: 8.4.0
[09:57:44.580] [UhkOperations] Operating system: Darwin 17.7.0 x64
[09:57:44.580] [UhkOperations] Start flashing right firmware
[09:57:44.581] [UhkHidDevice] Start reenumeration, mode: Bootloader
[09:57:44.693] [UhkHidDevice] USB[T]: Enumerate device. Mode: Bootloader
[09:57:44.693] [UhkHidDevice] USB[W]: 01 00 88 13 00 00 
[09:57:45.077] [UhkHidDevice] reenumeration devices up
[09:57:45.077] [UhkHidDevice] Device communication closing.
[09:57:45.077] [UhkHidDevice] Device communication closed.
[09:57:45.078] [blhost] RUN: /Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[09:57:45.171] [blhost] EXIT_CODE: null
[09:57:45.171] [blhost] FINISHED: null
[09:57:45.172] [DeviceService] updateFirmware error { message: 'blhost error code:null',
  stack: 'Error: blhost error code:null\n    at finish (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[09:57:45.179] [UhkHidDevice] Available devices:
[09:57:45.180] {"vendorId":1452,"productId":632,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@1E,3/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Device Management/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":2198,"interface":-1,"usagePage":65280,"usage":11}
[09:57:45.180] {"vendorId":1452,"productId":632,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@1E,3/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Keyboard / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":2198,"interface":-1,"usagePage":1,"usage":6}
[09:57:45.180] {"vendorId":1452,"productId":632,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@1E,3/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Trackpad / Boot/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":2198,"interface":-1,"usagePage":1,"usage":2}
[09:57:45.180] {"vendorId":1452,"productId":632,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@1E,3/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Actuator/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":2198,"interface":-1,"usagePage":65280,"usage":13}
[09:57:45.180] {"vendorId":1452,"productId":632,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SPI1@1E,3/AppleIntelLpssGspi@1/AppleIntelLpssSpiController@1/AppleIntelLpssSpiDevice@0/AppleHSSPIController/Apple Internal Keyboard / Trackpad/Accelerometer/AppleHSSPIHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Internal Keyboard / Trackpad","release":2198,"interface":-1,"usagePage":65280,"usage":3}
[09:57:45.180] {"vendorId":1452,"productId":34304,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS03@14200000/iBridge@14200000/IOUSBHostInterface@6/IOUSBHostHIDDevice@14200000,6","serialNumber":"","manufacturer":"Apple Inc.","product":"iBridge","release":257,"interface":-1,"usagePage":32,"usage":65}
[09:57:45.181] {"vendorId":1452,"productId":34304,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS03@14200000/iBridge@14200000/IOUSBHostInterface@2/IOUSBHostHIDDevice@14200000,2","serialNumber":"","manufacturer":"Apple Inc.","product":"iBridge","release":257,"interface":-1,"usagePage":13,"usage":5}
[09:57:45.181] {"vendorId":1133,"productId":49257,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/IOUSBHostDevice@14410000/AppleUSB20Hub@14410000/AppleUSB20HubPort@14414000/IOUSBHostDevice@14414000/AppleUSB20Hub@14414000/AppleUSB20HubPort@14414100/USB Laser Mouse@14414100/IOUSBHostInterface@0/IOUSBHostHIDDevice@14414100,0","serialNumber":"","manufacturer":"Logitech","product":"USB Laser Mouse","release":22017,"interface":-1,"usagePage":1,"usage":2}
[09:57:45.181] {"vendorId":2830,"productId":773,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/IOUSBHostDevice@14410000/AppleUSB20Hub@14410000/AppleUSB20HubPort@14412000/IOUSBHostDevice@14412000/AppleUSB20Hub@14412000/AppleUSB20HubPort@14412200/Jabra EVOLVE LINK MS@14412200/IOUSBHostInterface@3/IOUSBHostHIDDevice@14412200,3","serialNumber":"0000521231FE07","manufacturer":"GN Netcom A/S","product":"Jabra EVOLVE LINK MS","release":769,"interface":-1,"usagePage":11,"usage":5}
[09:57:45.181] {"vendorId":7504,"productId":24864,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14400000/USB2.0 Hub@14400000/AppleUSB20Hub@14400000/AppleUSB20HubPort@14410000/IOUSBHostDevice@14410000/AppleUSB20Hub@14410000/AppleUSB20HubPort@14413000/UHK Bootloader@14413000/MCU HID GENERIC DEVICE@0/IOUSBHostHIDDevice@14413000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[09:57:45.181] {"vendorId":5824,"productId":10203,"path":"IOService:/IOResources/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_v060800/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_UserClient_v060800/org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v060800","serialNumber":"pqrs.org:org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v060800","manufacturer":"pqrs.org","product":"Karabiner VirtualHIDKeyboard","release":0,"interface":-1,"usagePage":1,"usage":6}
[09:57:45.181] {"vendorId":1452,"productId":34304,"path":"IOService:/IOResources/IOHIDResource/IOHIDResourceDeviceUserClient/IOHIDUserDevice","serialNumber":"","manufacturer":"","product":"","release":0,"interface":-1,"usagePage":1,"usage":6}
[09:57:45.182] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.waitUntilKeyboardBusy (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:138:1)
    at DeviceService.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/src/services/device.service.ts:137:31)
    at Generator.next (<anonymous>)

[09:57:45.183] [blhost] CLOSE_CODE: null
[09:57:45.693] [DeviceService] Device connection state changed to: { bootloaderActive: true, connected: false, hasPermission: true }
blhost error code:null
```

I can update (or at least try) from a different computer (Windows). Unless you need more information from me or prefer that I wait for another agent / firmware version.

**Comment by mondalaci** [comment] 2018-08-08 17:15
This is definitely a step forward. How is your monitor's USB hub conneced to your Mac? Directly via one of its USB ports, or via your USB adapter?

**Comment by MyDogTom** [comment] 2018-08-09 07:26
via USB adapter (same model)

**Comment by mondalaci** [comment] 2018-08-09 12:12
This is quite amusing. When directly connecting your UHK to the adapter, the adapter misbehaves. When connecting your UHK via the USB hub of your monitor directly, and via your adapter indirectly, it behaves.

Given your most recent log, this issue became a duplicate of #747. Please help out if you can and feel free to comment in it. I'm closing this issue.

**Closed by mondalaci** 2018-08-09 12:12 UTC
