### ISSUE TITLE
Touchpad constantly connecting and disconnecting

### ISSUE THREAD

**Issue by Slabity** [UltimateHackingKeyboard/agent#1563] opened 2021-08-06 21:32 UTC
Just got my touchpad today and I am seeing the following behavior after connecting it:

![uhk-touchpad-glitch](https://user-images.githubusercontent.com/3788421/128572248-9d475a76-5975-4494-a3e0-7d535fd762b0.gif)

While `stdout` for the agent (using appimage-run on Linux) repeatedly spits out the following:

```
17:21:36.471 › [DeviceService] Device connection state changed to: {
  bootloaderActive: false,
  zeroInterfaceAvailable: true,
  hasPermission: true,
  halvesInfo: {
    areHalvesMerged: false,
    isLeftHalfConnected: true,
    leftModuleSlot: 0,
    rightModuleSlot: 0
  },
  hardwareModules: {
    moduleInfos: [ '[object]', '[object]' ],
    rightModuleInfo: {
      firmwareVersion: '8.10.10',
      deviceProtocolVersion: '4.7.1',
      moduleProtocolVersion: '4.1.0',
      userConfigVersion: '4.2.0',
      hardwareConfigVersion: '1.0.0'
    }
  },
  multiDevice: false,
  connectedDevice: {
    id: 1,
    name: 'UHK 60 v1',
    vendorId: 7504,
    keyboardPid: 24866,
    bootloaderPid: 24864,
    buspalPid: 24865
  }
}
```

With `moduleInfos` constantly changing between `[ '[object]', '[object]' ]` and `[ '[object]' ]`

I should note that the contacts on my keyboard were dirty at first and the touchpad was not able to work at all. However, it's been cleaned and it doesn't seem to have any issues when I connect the left-half of the keyboard to those contacts.

Strangely enough, the touchpad actually works for input and I don't notice any sort of 'dropouts' when using it. The only issue I am having is the agent keeps saying it's connected/disconnected. The side-effect is that I can't configure it at all.

I'm using the latest version of the Linux AppImage (UHK.Agent-1.5.15-linux-x86_64.AppImage).

**Comment by mondalaci** [comment] 2021-08-07 06:58
Duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/364

**Closed by mondalaci** 2021-08-07 06:58 UTC
