### ISSUE TITLE
modifying value of key with basic modifier (shift,...)

### ISSUE THREAD

**Issue by sribst** [UltimateHackingKeyboard/agent#947] opened 2019-05-10 14:18 UTC
I think that SHIFT should be consider as any of the other modifier and have it's own layer because it's what is is.

I would like to be able to customise my config in order to have an azerty layout but it's impossible because the number row can't be switch.

Thanks for the awesome work

**Comment by mondalaci** [comment] 2019-05-10 14:21
Thanks for your suggestion! This is a duplicate of #617.

**Closed by mondalaci** 2019-05-10 14:21 UTC
