### ISSUE TITLE
Marco Controles for Backlighting/LED's

### ISSUE THREAD

**Issue by sferich888** [UltimateHackingKeyboard/agent#1641] opened 2021-12-02 23:44 UTC
I would like to have my UHK go to 'sleep' (if you will), and have its LED's dim or turn off; when the keyboard is not in use (as it is for some 8+ hrs of the day when I am sleeping, or away from my computer. 

As such; I would like to have the ability (with a marco; or some other functional method) to denote that the keyboard is not active or has not been active for X amount of time (2-5 minutes); and then have the keyboard take some action (like dimming/switching off the LED's/Backlighting).

**Comment by mondalaci** [comment] 2021-12-03 08:51
Duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/426

**Closed by mondalaci** 2021-12-03 08:51 UTC
