### ISSUE TITLE
Remapped key set back to default during update, agent still displays remapped combo

### ISSUE THREAD

**Issue by dustyculler** [UltimateHackingKeyboard/agent#1493] opened 2021-04-28 19:55 UTC
I've had my buttons in the bottom of the case (below Mod + Space) set to change virtual desktops in Windows for some time.  After updating to Agent 1.5.12 and firmware 8.10.9, Agent still displayed the left button as Ctrl+Win+Left arrow, however the key was functioning as a space key, which I believe is the default.

Remapping it to what it was already showing & saving restored it to the desired behavior.  Other remapped keys appear to be working properly, this is the only one I've noticed so far that had this issue.

Thanks.

**Comment by mondalaci** [comment] 2021-04-29 20:49
Thanks for reporting this issue! We haven't encountered this one yet.

Is there anybody else with the same issue? I'd like to see consistently reproducible steps, and then we'd look into it.

**Comment by mondalaci** [comment] 2021-05-23 20:20
I'm sure it's a duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/361

**Closed by mondalaci** 2021-05-23 20:20 UTC
