### ISSUE TITLE
Adjust LED brightness with keybinds

### ISSUE THREAD

**Issue by matthewgrossman** [UltimateHackingKeyboard/agent#1406] opened 2020-12-24 08:27 UTC
Is there any way to create a key mapping to modify the UHK's LED brightness? My keyboard lives in my bedroom and I'd like to easily toggle the red lights on/off without having to enter Agent

I don't see anything obvious from poking around Agent, but I could be missing something

**Comment by mondalaci** [comment] 2020-12-24 20:29
Not yet, but we'll make it happen. Closing this issue as a duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/315

**Closed by mondalaci** 2020-12-24 20:29 UTC
