### ISSUE TITLE
Add keymap UI

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#78] opened 2016-08-15 17:13 UTC
I've just created a mockup of the add keymap UI:

![agent-add-keymap](https://cloud.githubusercontent.com/assets/300402/17671638/55d1953a-6318-11e6-879d-b515c29d6cda.png)

The UI should be shown when clicking on the + button of the Keymaps row of the side menu.

The Search input should function as an incremental filter and only reveal the relevant filtered keymaps. The "x / y keymaps shown" text should also update accordingly.

The description field is not yet included into the keymap data structure but maybe it'd be useful all across Agent. I can see it being used when sharing keymaps in the future.

The keymap itself should be visualized just as when being edited but here no edit mode should be provided. The viewer should be put into view mode, so the popover should not pop up when clicking on the keys. Merely a tooltip should appear when hovering above a key showing relevant key mapping information.

Upon clicking the "Add keymap" button the relevant keymap should be added.

If a keymap with the same name already exist then let's append " (2)" to its end. If that's already exists then " (3)", and so forth.

If a keymap with the same abbreviation already exists then let's use "2" as the last letter, then increment it. For example "QWR" -> "QW2" -> "QW3" -> ... -> "QW9" -> then go over the alphabet: "QWA" -> "QWB" -> .. -> "QWZ" -> then just start from "AAA" and increment ("AAA" -> "AAB" -> ... -> "AAZ" -> ABA -> ...) until a free abbreviation is found.

This is a rough mockup and many details could probably be more polished. Smaller layer buttons may look better and maybe the "Add keymap" button should be full width.

Suggestions are welcome!

**Comment by NejcZdovc** [comment] 2016-08-16 16:26
Sounds good, but I have some question:

1. Should we add description to the keymap when implementing add keymap?
2. Should slider be included in this list? (so you can slide between layers)
3. What relevant key mapping information would you like to show in popup?
4. Where would we have list of all keymaps available for adding? Will this be a new JSON that needs to be added to the project?

**Comment by mondalaci** [comment] 2016-08-16 18:10
Yours are excellent questions, Nejc. Exactly the stuff that I should have included into the issue. :)

1. For the time being, let's only use descriptions for the hardcoded keymaps of the Add new keymap page.
2. I'm not sure what you mean. Switching between layers is already possible with the Base, Mod, Fn, Mouse buttons per layer.
3. Something like this should be displayed in a tooltip tailored on a per key action basis: Key action: keypress[newline]Scancode: A[newline]Modifiers: none[newline]Long press action: None
4. Yep, a dedicated JSON file would be perfect for this purpose. You're welcome to create a JSON file with some example layouts. As soon as the keymap editor gets fully usable I will export and add a number of layouts to this file.

**Comment by NejcZdovc** [comment] 2016-08-17 14:54
Ok, so far so good. Will start working on this and can talk more about it on the way. More about progress here #80

**Comment by fjozsef** [comment] 2016-08-18 07:53
This issue seems to me the duplicate of #11

**Comment by mondalaci** [comment] 2016-08-18 12:50
Good catch, my bad. Just closed #11.

**Comment by fjozsef** [comment] 2016-08-28 09:45
Is this issue the keymap editor from #18 ?

**Comment by NejcZdovc** [comment] 2016-08-28 09:50
I think he was talking about keymap edit, not add. I already ported all scss to the angular in #72, so I think #18 can be closed.

**Comment by NejcZdovc** [comment] 2016-08-28 09:55
Correction. One thing that needs to be done is to add bootstratp scss to the project. Now we are including whole css.

**Comment by NejcZdovc** [comment] 2016-08-29 20:06
Closing as it was just merged to the master.

**Closed by NejcZdovc** 2016-08-29 20:06 UTC

**Comment by fjozsef** [comment] 2016-08-30 06:50
Add keymap button is not working. We either should reopen this issue or create other ones for the rest of the functionalies including the keyaction to label conversion for the tooltip.

**Comment by NejcZdovc** [comment] 2016-08-30 07:17
I wanted to implement all save functionalities in data layer PR, that's why I closed this issue.

**Comment by fjozsef** [comment] 2016-08-30 09:47
I know, but the issue's description is about more and there are missing functionalities described in https://github.com/UltimateHackingKeyboard/agent/issues/78#issue-171215656.
