### ISSUE TITLE
UHK v2 Not detected after 2.0.0 Agent firmware update 

### ISSUE THREAD

**Issue by alevani** [UltimateHackingKeyboard/agent#1875] opened 2022-10-24 09:31 UTC
Since the 2.0.0 update my UHK Keyboard is not detected by the Agent. It used to work just fine. I have attempted to reboot my computer, close and open the program, unplug and plug the keyboard again, nothing does it.

I have a Macbook Pro M1 2021 on Monterey 12.4

It is hard to give a better diagnostic since nothing happens or appear - maybe you can direct me to an action for a better diagnostic?

**Comment by mondalaci** [comment] 2022-10-24 09:56
Duplicate of #1873. Please let's discuss this further there.

**Closed by mondalaci** 2022-10-24 09:56 UTC
