### ISSUE TITLE
[Feature request] Add touchpad module support for two- finger scrolling

### ISSUE THREAD

**Issue by bonstio** [UltimateHackingKeyboard/agent#1587] opened 2021-09-10 11:32 UTC
As alluded to here [https://ultimatehackingkeyboard.com/manuals/touchpad], at some point the touchpad module will support two-finger scrolling. I'm creating this issue to track this feature request

**Comment by mondalaci** [comment] 2021-09-10 12:27
Closing this issue as a duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/387

**Closed by mondalaci** 2021-09-10 12:27 UTC
