### ISSUE TITLE
Periodic glitches when agent is open

### ISSUE THREAD

**Issue by strowk** [UltimateHackingKeyboard/agent#2120] opened 2023-10-21 22:57 UTC
When I open Agent, periodically keyboard glitches and does not receive any input and last key entered might stuck and be entered several times.

There is no specific time between glitches, there are times between them I have measured: 
<img width="65" alt="image" src="https://github.com/UltimateHackingKeyboard/agent/assets/25692644/c2c6a6b7-2188-4151-8e8b-000c69964037">

**Comment by mondalaci** [comment] 2023-10-22 09:25
There must be something unusual with your hardware configuration because none of the three issues you have reported occur to others.

Please make sure that your UHK is not connected via a KVM switch, docking station, or USB hub, and your OS is not running in a virtual machine. Please also try to reproduce these issues on another computer, preferably with a new OS installation.

I'm closing your other issues because they must be related to this one.

**Comment by mondalaci** [comment] 2023-11-14 11:24
Closing this issue due to lack of replies. Feel free to follow up at any time.

**Closed by mondalaci** 2023-11-14 11:24 UTC

**Comment by porceCodes** [comment] 2023-11-17 23:20
I have the same issue. Agent version 3.2.1 and the previous ones. I flashed the firmware whenever I updated the Agent. 
The period of glitches is every couple minutes in my case.

**Comment by porceCodes** [comment] 2023-11-17 23:21
Please reopen.

**Comment by mondalaci** [comment] 2023-11-19 20:23
This shouldn't be an Agent issue.

Please let's troubleshoot based on [this guide](https://ultimatehackingkeyboard.com/repair/fixing-misbehaving-keys) and follow up via [our contact form](https://ultimatehackingkeyboard.com/contact-us).
