### ISSUE TITLE
Agent LED not activated but the Agent is running.

### ISSUE THREAD

**Issue by qwc** [UltimateHackingKeyboard/agent#851] opened 2018-11-04 12:19 UTC
This particular thing is on the list of features for the Agent and the keyboard, as far as I can remember. (haven't double checked)

So I am using Arch Linux, KDE/Plasma, if further detailed information is needed, tell me.

And the LED with the Agent icon does not lit up, when the agent is running.

Also got the info of a fellow UHK user on discord, that with his Mac laptop and the agent running, the LED also does not work.

**Comment by dancek** [comment] 2018-11-04 12:46
The LED doesn't light up on Windows 10 or macOS either.

**Comment by mondalaci** [comment] 2018-11-04 12:50
This is a firmware issue. Duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/126

**Closed by mondalaci** 2018-11-04 12:50 UTC
