### ISSUE TITLE
Show the loading screen until the configuration gets loaded

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#431] opened 2017-10-05 21:59 UTC
Currently, as soon as the UHK gets connected, Agent switches from the loading screen to the main application screen featuring the keyboard, then later when it loads the configuration from the UHK it updates the configuration on the screen, which is rather disturbing.

Please only switch to the main application screen when the configuration gets loaded.

**Comment by ert78gb** [comment] 2017-10-05 22:00
Is not duplicate of #296 ?

**Comment by mondalaci** [comment] 2017-10-05 22:01
Related, but not duplicate.

**Closed** 2017-10-13 23:22 UTC
Labels: enhancement
