### ISSUE TITLE
JavaScript error when quickly resizing window while Agent is starting

### ISSUE THREAD

**Issue by mhantsch** [UltimateHackingKeyboard/agent#2333] opened 2024-08-08 13:03 UTC
This has been happening on many versions of Agent in the last 2 years, but until now I was too occupied to report it.

OS: Windows, doesn't matter if 10 or 11.

If I start Agent, and directly after it opens its window, grab the corner and resize it, I often get this error:

![image](https://github.com/user-attachments/assets/c96f2af3-24e8-4035-8ea5-3396a4882088)

If you take longer until you grab and resize, everything works without error.

**Comment by mondalaci** [comment] 2024-08-08 14:33
I've tried to reproduce this issue about a dozen times on Windows 11 Home 23H2 unsuccessfully. Nobody has reported it yet.

@ert78gb Can you reproduce it? Any ideas on fixing it?

**Comment by mhantsch** [comment] 2024-08-22 10:10
It just happened again. I am wondering if it may have to do with multiple monitors and different resolutions on each of them. My main monitor is UHD resolution (screen 2) and Agent opens on a different monitor with HD resolution (screen 4). when I dragged the size corner, again I got the message.

![image](https://github.com/user-attachments/assets/dfba4b7a-5a82-4565-9f1c-019d00b2c17d)

Once I click the message away (OK button), it does not reappear if I resize it again. Also, today it did not reappear after closing and reopening Agent. It's really weird.

**Comment by ert78gb** [comment] 2024-08-24 10:55
I investigated it and looks like the windows resize event triggering more frequently than the OS able to save this information into a file and 2 saving are conflicting. 

I need little bit more time to figure it out the simple debounce will solve the issue. Or we have to contribute in the underlying `electron-settings` library.

**Comment by mhantsch** [comment] 2024-08-24 13:33
@ert78gb Are you saving the window position and size immediately each time the position or size change? Is this for the next restart of the app (so that it opens where it was open before?) If that is a yes, then I would be perfectly fine if you just saved the window position and size just once on exiting the app.

**Comment by ert78gb** [comment] 2024-08-24 14:14
Yes, we save the window state, when resize, move and closing the app. Just to be sure we don't loose these information when the app crashes.

Save the state only on exit could be a solution too. @mondalaci the choice is yours.

**Comment by mondalaci** [comment] 2024-08-24 14:20
Saving state on exit is fine.

**Closed** 2024-09-01 17:15 UTC
