### ISSUE TITLE
Remapping Fn key does not work up for Mod and Mouse layers in Agent

### ISSUE THREAD

**Issue by Makistos** [UltimateHackingKeyboard/agent#1044] opened 2019-09-18 13:59 UTC
I tried to switch Alt and Fn keys (as I think Alt should be closest to space) but noticed that after doing this on the Base layer and selecting both "Remap on all layers" and "Remap on all keymaps" that the Agent still shows both keys as Alt for those two layers. 

Layer switching is only possible from Base layer but this logic is a bit odd because the keys do show up correctly on the Fn layer. I think those layers should still show the keys correctly or alternatively not show those keys at all.

**Comment by mondalaci** [comment] 2019-09-18 18:38
> I tried to switch Alt and Fn keys (as I think Alt should be closest to space) but noticed that after doing this on the Base layer and selecting both "Remap on all layers" and "Remap on all keymaps" that the Agent still shows both keys as Alt for those two layers.

For which two layers? When I check both the "Remap on all layers" and "Remap on all keymaps" checkboxes, Agent correctly displays Alt instead of Fn on every layer of every keymap for the remapped key.

Which Agent version are you using?

> Layer switching is only possible from Base layer but this logic is a bit odd because the keys do show up correctly on the Fn layer. I think those layers should still show the keys correctly or alternatively not show those keys at all.

Layer switcher actions show up on the base layer and on their own layer. This makes sense because you can only switch to a non-base layer from the base layer. You can assign other actions to other layers.

**Comment by Makistos** [comment] 2019-09-19 08:14
Alt is displayed yes, but Fn isn't. It just looks weird to me that now I have four alt keys in those two other layers.

**Comment by mondalaci** [comment] 2019-09-19 09:06
I have finally figured out what you mean. When changing a key from Alt to Fn and checking the "Remap on all layers" checkbox, Alt only gets changed on the Base and Fn layers.

The reason it looks weird is because all of the layers of the key contain the same action. It's possible that they all contain different actions in which case it makes sense to preserve the layers which don't need to be changed.

This is not a bug, so I'm closing this issue.

**Closed by mondalaci** 2019-09-19 09:06 UTC
