### ISSUE TITLE
Allow Space and Dash in 3-Character Keymap Abbreviations

### ISSUE THREAD

**Issue by NickDaly** [UltimateHackingKeyboard/agent#863] opened 2018-11-17 17:29 UTC
The keymap abbreviations don't allow for space or dash characters even though the display can show those characters.  For example, I would like to name my Emacs keymap "M-X or "M X", neither of which is currently possible.

Other useful characters might include +, and |.

Definitely not a big deal at all, it would just be fun to have.  Thanks for reading!

**Comment by mondalaci** [comment] 2018-11-17 17:51
Duplicate of #765.

**Closed by mondalaci** 2018-11-17 17:51 UTC

**Comment by vinipsmaker** [comment] 2019-03-02 02:05
Hey @NickDaly, I'm also an Emacs user. Just out of curiosity, what is an Emacs keymap? Could you list your main customizations please?

**Comment by NickDaly** [comment] 2019-03-02 04:22
@vinipsmaker it's one where the bottom row is rearranged and Capslock is
changed out for Alt or Ctrl.  For ideas, see the Emacs wiki:

https://www.emacswiki.org/emacs/SwapControlAltAndCapsLock#toc8

My Capslock is an Alt, and bottom row is:

Super/Windows - Fn - Mouse - Ctrl - Space /  / Ctrl - Alt - Meta - Mouse -
Fn

My left and right switches are bound to meta and mouse.  It leaves me with
only one spacebar but it puts the useful modifier keys in easy reach.

**Comment by kareltucek** [comment] 2019-03-02 09:47
Btw, I don't like the idea of allowing space in abbreviations very much. (Referring to names which do not include space is so much easier...)

Also, as far as I understand written text, the #765 only talks about adding support for those characters, not about allowing them in abbreviations, so I see nothing strictly duplicit about the issues.
