### ISSUE TITLE
Error after deleting macros

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent#194] opened 2016-11-27 16:48 UTC
I reset local storage, delete every macro, go to the VIM keymap, and get this:

![untitled](https://cloud.githubusercontent.com/assets/300402/20649892/a4cf0070-b4c9-11e6-871e-36f707b5b10d.png)

**Comment by fjozsef** [comment] 2016-11-27 16:50
Possibly duplicate of #140

**Comment by mondalaci** [comment] 2016-11-27 17:02
Good catch! Yes, it's possibly a duplicate. We should look into it.

**Closed** 2016-11-30 08:05 UTC
