### ISSUE TITLE
Impossible to use some special character into a Macro write text action.

### ISSUE THREAD

**Issue by saratry** [UltimateHackingKeyboard/agent#1727] opened 2022-03-03 17:28 UTC
**Problem:**
Some special characters (altcode > 122) are not properly mapped to the correct character when used into a Macro.
More specifically, a lot of accented letters are not mapped with anything. When these letter are inside a write text action into a Macro, they are not written.

**How to reproduce it:**
Create a new macro.
Add a write text action.
Enable NumLock, hold Alt and digit 133 (just an example)
You should see à written in the text box.
Save the macro.
Map the macro.
Save to the keyboard.
If you try to use the macro, nothing happens.

**Tested with:**
Agent version 1.5.17
UHK firmware version 8.10.12
Keymap QWERTY for PC
Windows 11 PRO

**Comment by mondalaci** [comment] 2022-03-04 08:39
Agent shouldn't accept non-ASCII characters, such as "à", in the text macro action field to begin with, but apparently, it does accept them when entered via Alt codes. We'll make Agent disallow non-ASCII characters from all sources.

Agent interprets the characters of text macro actions according to the US English keymap and sends USB scancodes accordingly. [This article](https://ultimatehackingkeyboard.com/blog/2018/06/23/how-can-i-type-accented-characters-with-my-uhk) contains more information on related issues.

The workaround is to use the characters of the relevant keys according to the US English layout. For example, the "à" key on the Italian layout is in the same position as the apostrophe key on the US English layout, hence, apostrophe should be written into the text macro action instead of "à".

**Comment by saratry** [comment] 2022-03-04 12:32
This works only if I set the Italian keyboard layout in Windows. I was using the UK English layout.
But I wouldn't need the Macro in the first place if I use the Italian layout, since these letters are already available.
My goal was to use the UK English layout and to use Macro (mapped to Fn layer) for special characters that are not present in that keyboard layout. 

From what I understand now it is not possible to write any character that is not originally present in the OS keyboard layout, am I correct?

**Comment by mondalaci** [comment] 2022-03-04 13:39
Correct. According to the linked article, USB keyboards, such as the UHK, don't send characters but scancodes to the host computer. The scancodes, in turn, are translated to characters by the OS according to the current layout.

It's possible to write characters not originally present in the OS keyboard layout via Alt codes. According to the article I previously linked, the implementation of Alt codes is OS-specific. UHK macros can implement Alt codes.

**Comment by saratry** [comment] 2022-03-04 17:05
Thank you, implementing Alt codes with macro works like a charm. 
This solves my problem: can I close the issue or do you want to keep it to prevent the usage of Alt code inside the write text action?

**Comment by mondalaci** [comment] 2022-03-04 17:32
Glad to help!

Yes, we want to prevent using Alt codes in the write text action.

**Comment by p-m-j** [comment] 2022-04-14 09:30
I posted a message to the support mailbox, but if anyone has a sec to help out..

Am i going mad or is it not possible to add `\` to a TextMacroAction from a UK ISO UHK v2 layout?

**Comment by kareltucek** [comment] 2022-04-14 10:05
See https://github.com/UltimateHackingKeyboard/firmware/blob/master/right/src/macro_shortcut_parser.c#L20 .

If your table is correct, then you need to insert '/' in place of your '\', since US ISO /? scancode is 56 (which I believe is what you want).

Generally, following process for inserting characters into write text action should work:
1) Switch your OS layout to en-US. (Strangely, I don't remember to having choose between ANSI enUS and ISO enUS layout ever.)
2) Tap your keys as if it was your native OS keyboard layout.
3) Switch back to your preferred OS native layout.

Does this help, or have I misunderstood you totally?

**Comment by p-m-j** [comment] 2022-04-14 10:15
> Generally, following process for inserting characters into write text action should work:
> 
>     1. Switch your OS layout to en-US. (Strangely, I don't remember having to choose between ANSI enUS and ISO enUS layout ever.)
> 
>     2. Tap your keys as if it was your native OS keyboard layout.
> 
>     3. Switch back to your preferred OS native layout.

I tried these steps with both "English (US)" and "English (US, alt. intl.)" 
For the former when I switch back I get a `#` for the latter when I switch back I get a `<`

**Comment by p-m-j** [comment] 2022-04-14 10:24
I guess this is something to do with `HID_KEYBOARD_SC_BACKSLASH_AND_PIPE` vs `HID_KEYBOARD_SC_NON_US_BACKSLASH_AND_PIPE`

**Comment by kareltucek** [comment] 2022-04-14 10:43
Oh, I see. Yes.

Since both those scancodes produce same character in enUS, the reverse mapping cannot distinguish them and goes always to the same `HID_KEYBOARD_SC_BACKSLASH_AND_PIPE`. This is indeed a problem with layout which maps those two keys (`\|` and `|ISO`) to different characters. So you indeed cannot get `\` out of write text action with gb layout.

I am afraid you will have to use the tap key action to get the correct scancodes.

**Comment by p-m-j** [comment] 2022-04-14 10:55
You're a star that works!

![backslash_cdot](https://user-images.githubusercontent.com/2056399/163377245-3d6e8802-5930-436e-9f13-3c8352b7648f.png)

But it's a right faff to work this out, I wonder if there's an alternative setup for the firmware that would work?
Or if the agent needs hex input option?

There must be some way to make this a little more intuitive

**Comment by kareltucek** [comment] 2022-04-14 11:09
The entire problem of making UHK/Agent non-en-US friendly is a complex one, and we are not aware of a solution which would work reasonably well across all platforms. (Specifically, we are missing some library which would be able to query the OS scancode <-> character mapping under all major OSes. Even then, implementing and maintaining such solution would probably not be a simple task.)

Having said this, I still encourage anyone with too much free time to challenge this claim and to prove otherwise!

**Comment by p-m-j** [comment] 2022-04-14 11:25
> Even then, implementing and maintaining such solution would probably not be a simple task

There are only two layouts available for UHK v2 at present, the ISO layout and the ANSI layout so it seems to me from an outsider perspective that it could be handled with two maps in macro_shortcut_parser.c + a param for MacroShortcutParser_CharacterToScancode to differentiate.

**Comment by kareltucek** [comment] 2022-04-14 12:01
I was thinking much more in terms of global key labeling and in terms of write action text not corresponding with keyboard layout with non-english layouts in general.

I see your point w.r.t. ISO/ANSI backslash, but fixing that one character still does not make the reverse mapping ISO compliant, does it? If I understand you correctly, your proposal basically implies that we should also switch hardware-ISO-UHK's macro reverse mapping from standard en US layout to US international. (That means changing mapping for `#~\|£¬@"` characters.) This would mean instantly breaking setups of many users who seem to be happy with the ANSI US layout.

**Comment by kareltucek** [comment] 2022-04-14 12:05
(It would also make support much more troublesome, as problems similar to your would become dependent on hardware version, and therefore much harder to reprocude and debug.)

**Comment by p-m-j** [comment] 2022-04-14 12:05
Quirks mode flag :D

**Comment by mondalaci** [comment] 2022-04-14 14:15
The type text macro action feature is fundamentally misleading because it falsely suggests that the UHK sends characters instead of scancodes, resulting in issues and misunderstandings like this. The best workaround is to use the tap key action featuring the ISO key as suggested above, and there's no real solution.

I keep this issue open because we want to prevent entering invalid characters via Alt codes, and we'll only close this issue afterward.

**Comment by p-m-j** [comment] 2022-04-14 15:05
@mondalaci Is maintaining two maps not a real solution to my issue?

I can't press any key that will result in (INT1/ISO key) 0x64 being sent on playback.

But if I could opt into ISO layout mode via the macro editor UI and two maps were maintained in the firmware then it would work just fine, non uk iso folks will get a `<` and i'll get my `\` both as expected for iso layout.

**Comment by mondalaci** [comment] 2022-04-14 15:09
We wouldn't have to maintain two but hundreds of such maps for a complete solution.

**Comment by p-m-j** [comment] 2022-04-14 15:10
How so, there are only two layouts?

I'm talking about the ability to send scancodes not characters, I fully accepted I need to think in scancodes the second I read the help text in the UI.

**Comment by p-m-j** [comment] 2022-04-14 15:51
There’s a workaround for non UK iso though as the key is < which can be sent another way, it’s only the brits that are buggered :)

**Comment by kareltucek** [comment] 2022-04-14 15:52
@mondalaci the problem is that the write action reverse mapping does not cover standard iso **scancode**-space.

(I still call it "wont fix" as the write macro action is basically broken by design, because the issue can be easily workarounded and because the fix neither solves the problem as whole, nor provide reasonable benefit / trouble ratio.)

**Comment by mondalaci** [comment] 2022-04-14 15:54
@kareltucek I fully agree with you.

**Comment by p-m-j** [comment] 2022-04-14 15:55
Then the real fix is probably just a little more help text :)

**Comment by mondalaci** [comment] 2022-04-14 16:01
@p-m-j Thanks for your suggestion! We'll consider including it if we encounter more cases like yours. Even then, maybe we should rather extend the linked article because many related issues and misunderstandings can occur that can't be addressed in a short tooltip.

**Comment by kareltucek** [comment] 2022-04-14 16:15
> and what the playback character will be.

(That's the problem - we don't know what the character will be, otherwise we would probably have already implemented full fledged solution.)

**Comment by p-m-j** [comment] 2022-04-14 16:32
> > and what the playback character will be.
> 
> (That's the problem - we don't know what the character will be, otherwise we would probably have already implemented full fledged solution.)

🤦 right, best you can do is display the input -> scan code

**Closed** 2022-12-29 17:24 UTC
