### ISSUE TITLE
Firmware update failed, device not functioning

### ISSUE THREAD

**Issue by mattgrosse** [UltimateHackingKeyboard/agent#876] opened 2018-12-14 01:53 UTC
I believe I was updating from Agent 1.2.6 to the latest. Agent loaded fine but when I went to upgrade the firmware it failed and the keyboard led went blank. Sadly I do not have a capture of the output from that firmware upgrade attempt. After reading some of the issues, I tried the hardware reset and loaded up Agent 1.2.11. I can get to the Fix Device screen, but it is failing with the following output:

```
[20:45:13.062] [UhkOperations] Operating system: Darwin 17.5.0 x64
[20:45:13.063] [UhkOperations] Start flashing right firmware
[20:45:13.063] [UhkHidDevice] Start reenumeration, mode: Bootloader
[20:45:13.069] [UhkHidDevice] reenumeration devices up
[20:45:13.070] [UhkHidDevice] Device communication closing.
[20:45:13.071] [blhost] RUN: /Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[20:45:13.112] [blhost] STDOUT: Inject command 'flash-security-disable'
Successful generic response to command 'flash-security-disable'
Response status = 0 (0x0) Success.

[20:45:13.116] [blhost] EXIT_CODE: 0
[20:45:13.117] [blhost] FINISHED: 0
[20:45:13.117] [blhost] RUN: /Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost --usb 0x1d50,0x6120 flash-erase-region 0xc000 475136
[20:45:13.127] [blhost] CLOSE_CODE: 0
[20:45:18.149] [blhost] STDOUT: Inject command 'flash-erase-region'
sendCommandGetResponse.readPacket error 5.
Response status = 10004 (0x2714) No response packet from target device.

[20:45:18.151] [blhost] EXIT_CODE: 20
[20:45:18.151] [blhost] FINISHED: 20
[20:45:18.153] [DeviceService] updateFirmware error { message: 'blhost error code:20',
  stack: 'Error: blhost error code:20\n    at finish (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[20:45:18.160] [UhkHidDevice] Available devices:
[20:45:18.160] {"vendorId":0,"productId":0,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SBUS@1F,3/AppleSMBusPCI/BUS0@0/AppleSMBusControllerICH/MKY0/AppleMikeyDriver/AppleMikeyHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Mikey HID Driver","release":0,"interface":-1,"usagePage":12,"usage":1}
[20:45:18.160] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Apple Internal Keyboard@0/AppleUSBTCKeyboard@1d182000,0","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":1,"usage":6}
[20:45:18.160] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Touchpad@2/AppleUSBTCButtons@1d182000,2","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":1,"usage":2}
[20:45:18.161] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Touchpad@1/AppleUSBMultitouchDriver@1d182000,1","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":65280,"usage":1}
[20:45:18.161] {"vendorId":7504,"productId":24864,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/PRT1@14100000/UHK Bootloader@14100000/MCU HID GENERIC DEVICE@0/IOUSBHostHIDDevice@14100000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[20:45:18.162] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)

[20:45:18.163] [blhost] CLOSE_CODE: 20
blhost error code:20
```

**Comment by mondalaci** [comment] 2018-12-14 05:05
Please merge the keyboard halves, remove the bridge cable, and retry the firmware update a couple of times.

**Comment by mattgrosse** [comment] 2018-12-14 14:09
Unfortunately, that didn't seem to change anything. I tried running it multiple times.


```
[09:07:48.998] [UhkOperations] Operating system: Darwin 17.5.0 x64
[09:07:48.998] [UhkOperations] Start flashing right firmware
[09:07:49.098] [UhkHidDevice] Start reenumeration, mode: Bootloader
[09:07:49.104] [UhkHidDevice] reenumeration devices up
[09:07:49.105] [UhkHidDevice] Device communication closing.
[09:07:49.106] [blhost] RUN: /Applications/UHK Agent.app/Contents/Resources/packages/blhost/mac/blhost --usb 0x1d50,0x6120 flash-security-disable 0403020108070605
[09:07:49.723] [blhost] EXIT_CODE: null
[09:07:49.723] [blhost] FINISHED: null
[09:07:49.725] [DeviceService] updateFirmware error { message: 'blhost error code:null',
  stack: 'Error: blhost error code:null\n    at finish (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:53:35)\n    at ChildProcess.childProcess.on.code (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/src/uhk-blhost.ts:36:17)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)' }
[09:07:49.731] [UhkHidDevice] Available devices:
[09:07:49.731] {"vendorId":0,"productId":0,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SBUS@1F,3/AppleSMBusPCI/BUS0@0/AppleSMBusControllerICH/MKY0/AppleMikeyDriver/AppleMikeyHIDDriver","serialNumber":"","manufacturer":"","product":"Apple Mikey HID Driver","release":0,"interface":-1,"usagePage":12,"usage":1}
[09:07:49.731] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Apple Internal Keyboard@0/AppleUSBTCKeyboard@1d182000,0","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":1,"usage":6}
[09:07:49.732] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Touchpad@2/AppleUSBTCButtons@1d182000,2","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":1,"usage":2}
[09:07:49.732] {"vendorId":1452,"productId":610,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EHC1@1D/EHC1@1d000000/PRT1@1d100000/IOUSBHostDevice@1d100000/AppleUSB20InternalIntelHub@1d100000/PRT8@1d180000/IOUSBHostDevice@1d180000/AppleUSB20InternalSMSCHub@1d180000/PRT2@1d182000/Apple Internal Keyboard / Trackpad@1d182000/Touchpad@1/AppleUSBMultitouchDriver@1d182000,1","serialNumber":"","manufacturer":"Apple Inc.","product":"Apple Internal Keyboard / Trackpad","release":546,"interface":-1,"usagePage":65280,"usage":1}
[09:07:49.732] {"vendorId":7504,"productId":24864,"path":"IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/PRT1@14100000/UHK Bootloader@14100000/MCU HID GENERIC DEVICE@0/IOUSBHostHIDDevice@14100000,0","serialNumber":"","manufacturer":"Ultimate Gadget Laboratories","product":"UHK Bootloader","release":2,"interface":-1,"usagePage":65280,"usage":1}
[09:07:49.733] [DeviceService] Read hardware modules information failed Error: [UhkHidDevice] Device is not connected
    at Promise (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:92:1)
    at Promise (<anonymous>)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:89:1)
    at Generator.next (<anonymous>)
    at /Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:7:1
    at Promise (<anonymous>)
    at __awaiter (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:3:1)
    at UhkHidDevice.write (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:88:1)
    at UhkHidDevice.<anonymous> (/Applications/UHK Agent.app/Contents/Resources/app.asar/webpack:/uhk-usb/dist/src/uhk-hid-device.js:140:1)
    at Generator.next (<anonymous>)

[09:07:49.734] [blhost] CLOSE_CODE: null
blhost error code:null
```

**Comment by mondalaci** [comment] 2018-12-14 16:02
There's actually a substantial change. `[blhost] FINISHED: null` means that blhost segfaulted, so the update would have likely succeeded if #755 was fixed.

Please retry the update on other computers in a merged state and without the bridge cable.

**Comment by mattgrosse** [comment] 2018-12-14 16:52
Ok great, I tried Agent 1.2.11 on a coworkers laptop (very similar to mine, and same version of OSX) and the upgrade worked. So I'm back in action. Strange that it was segfaulting on my machine and not his.

Should I assume it's not safe for me to run the firmware updater on my machine at the moment? I've done it in the past successfully, but this last experience was rough (as I use the keyboard for work).

**Comment by mondalaci** [comment] 2018-12-14 17:33
You can hardly brick your UHK, but based on the above, trying the firmware upgrade on your machine is probably pointless until #755 gets fixed.

Closing it as a duplicate of #755.

**Closed by mondalaci** 2018-12-14 17:33 UTC
