### ISSUE TITLE
Separate Mouse settings for each pointer mechanism

### ISSUE THREAD

**Issue by danpalmer** [UltimateHackingKeyboard/agent#1810] opened 2022-07-27 09:15 UTC
(Unsure if this is appropriate for the Agent or for the firmware, happy to re-write for the firmware)

The UHK supports many pointer mechanisms:
- Mouse keys
- Track ball
- Track pad
- Track point
- Track ball on key cluster module

Each of these behaves in different ways, meaning that one configuration for all produces unexpected results. For example, configuring a particular sensitivity for the trackball module, means that the mouse keys feel a little sluggish and the trackball on the key cluster feels very sluggish.

It would be great if each of these could be configured separately.

**Comment by mondalaci** [comment] 2022-07-27 13:12
Duplicate of https://github.com/UltimateHackingKeyboard/firmware/issues/351. Will be included in the next firmware and Agent release.

**Closed by mondalaci** 2022-07-27 13:12 UTC
